In [1]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.19.1-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from optuna) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from optuna) (26.3)
Collecting sqlalchemy>=1.4.2 (from optuna)
  Downloading sqlalchemy-2.0.52-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.6 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.13/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.13/dist-packages (from alembic>=1.5.0->optuna) (4.16.0)
Collecting greenlet>=1 (from sqlalchemy>=1.4.2->optuna)
  Downloading greenlet-3.5.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 12.6 MB/s eta 0:00:00
Downloading alembic-1.19.1-py3-none-any.whl (265 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.9/265.9 kB 26.3 MB/s eta 0:00:00
Downloading sqlalchemy-2.0.52-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 96.9 MB/s eta 0:00:00
Downloading colorlog-6.12.0-py3-none-any.whl (12 kB)
Downloading greenlet-3.5.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (623 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 623.9/623.9 kB 46.3 MB/s eta 0:00:00
Installing collected packages: greenlet, colorlog, sqlalchemy, alembic, optuna
Successfully installed alembic-1.19.1 colorlog-6.12.0 greenlet-3.5.5 optuna-4.9.0 sqlalchemy-2.0.52

In [2]:
import optuna
import pandas as pd
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [4]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [5]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [6]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())
study.optimize(objective, n_trials=20)

[I 2026-08-30 03:40:52,764] A new study created in memory with name: no-name-c34c77b1-5047-4d05-a247-4198dd28bf78
[I 2026-08-30 03:40:53,246] Trial 0 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 134, 'max_depth': 17}. Best is trial 0 with value: 0.7746741154562384.
[I 2026-08-30 03:40:53,801] Trial 1 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 156, 'max_depth': 14}. Best is trial 0 with value: 0.7746741154562384.
[I 2026-08-30 03:40:53,971] Trial 2 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 52, 'max_depth': 4}. Best is trial 0 with value: 0.7746741154562384.
[I 2026-08-30 03:40:54,313] Trial 3 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 95, 'max_depth': 16}. Best is trial 0 with value: 0.7746741154562384.
[I 2026-08-30 03:40:54,587] Trial 4 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 82, 'max_depth': 5}. Best is trial 0 with value: 0.7746741154562384.
[I 2026-08-30 03:40:54,815] Trial 5 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 69, 'max_depth': 4}. Best is trial 0 with value: 0.7746741154562384.
[I 2026-08-30 03:40:55,522] Trial 6 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 194, 'max_depth': 20}. Best is trial 0 with value: 0.7746741154562384.
[I 2026-08-30 03:40:56,162] Trial 7 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 199, 'max_depth': 3}. Best is trial 0 with value: 0.7746741154562384.
[I 2026-08-30 03:40:56,750] Trial 8 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 161, 'max_depth': 12}. Best is trial 0 with value: 0.7746741154562384.
[I 2026-08-30 03:40:57,301] Trial 9 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 142, 'max_depth': 17}. Best is trial 0 with value: 0.7746741154562384.
[I 2026-08-30 03:40:57,751] Trial 10 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 118, 'max_depth': 9}. Best is trial 0 with value: 0.7746741154562384.
[I 2026-08-30 03:40:58,460] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 193, 'max_depth': 20}. Best is trial 0 with value: 0.7746741154562384.
[I 2026-08-30 03:40:58,928] Trial 12 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 128, 'max_depth': 20}. Best is trial 12 with value: 0.7765363128491621.
[I 2026-08-30 03:40:59,378] Trial 13 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 122, 'max_depth': 17}. Best is trial 12 with value: 0.7765363128491621.
[I 2026-08-30 03:40:59,806] Trial 14 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 116, 'max_depth': 20}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-08-30 03:41:00,163] Trial 15 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 98, 'max_depth': 20}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-08-30 03:41:00,559] Trial 16 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 109, 'max_depth': 19}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-08-30 03:41:01,162] Trial 17 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 169, 'max_depth': 14}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-08-30 03:41:01,648] Trial 18 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 137, 'max_depth': 18}. Best is trial 14 with value: 0.7783985102420857.
[I 2026-08-30 03:41:02,022] Trial 19 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 103, 'max_depth': 15}. Best is trial 14 with value: 0.7783985102420857.

In [7]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7783985102420857
Best hyperparameters: {'n_estimators': 116, 'max_depth': 20}

In [8]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

### ***Samplers in Optuna***

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [10]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())
study.optimize(objective, n_trials=25)

[I 2026-08-30 03:41:02,195] A new study created in memory with name: no-name-35cad8ee-c864-4e51-bc5f-8ac3fb7ef3e8
[I 2026-08-30 03:41:02,693] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 139, 'max_depth': 11}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-08-30 03:41:02,968] Trial 1 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 76, 'max_depth': 8}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-08-30 03:41:03,298] Trial 2 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 92, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-08-30 03:41:03,683] Trial 3 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 110, 'max_depth': 8}. Best is trial 3 with value: 0.7709497206703911.
[I 2026-08-30 03:41:04,006] Trial 4 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 87, 'max_depth': 14}. Best is trial 3 with value: 0.7709497206703911.
[I 2026-08-30 03:41:04,518] Trial 5 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 141, 'max_depth': 10}. Best is trial 3 with value: 0.7709497206703911.
[I 2026-08-30 03:41:04,923] Trial 6 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 114, 'max_depth': 8}. Best is trial 3 with value: 0.7709497206703911.
[I 2026-08-30 03:41:05,440] Trial 7 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 141, 'max_depth': 16}. Best is trial 3 with value: 0.7709497206703911.
[I 2026-08-30 03:41:05,943] Trial 8 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 140, 'max_depth': 10}. Best is trial 3 with value: 0.7709497206703911.
[I 2026-08-30 03:41:06,617] Trial 9 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 191, 'max_depth': 13}. Best is trial 9 with value: 0.7728119180633147.
[I 2026-08-30 03:41:07,185] Trial 10 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 160, 'max_depth': 13}. Best is trial 9 with value: 0.7728119180633147.
[I 2026-08-30 03:41:07,690] Trial 11 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 147, 'max_depth': 6}. Best is trial 9 with value: 0.7728119180633147.
[I 2026-08-30 03:41:08,261] Trial 12 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 149, 'max_depth': 3}. Best is trial 9 with value: 0.7728119180633147.
[I 2026-08-30 03:41:08,634] Trial 13 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 90, 'max_depth': 13}. Best is trial 9 with value: 0.7728119180633147.
[I 2026-08-30 03:41:08,954] Trial 14 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 87, 'max_depth': 3}. Best is trial 9 with value: 0.7728119180633147.
[I 2026-08-30 03:41:09,716] Trial 15 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 177, 'max_depth': 12}. Best is trial 9 with value: 0.7728119180633147.
[I 2026-08-30 03:41:10,255] Trial 16 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 145, 'max_depth': 16}. Best is trial 9 with value: 0.7728119180633147.
[I 2026-08-30 03:41:10,932] Trial 17 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 187, 'max_depth': 20}. Best is trial 9 with value: 0.7728119180633147.
[I 2026-08-30 03:41:11,192] Trial 18 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 77, 'max_depth': 4}. Best is trial 9 with value: 0.7728119180633147.
[I 2026-08-30 03:41:11,854] Trial 19 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 187, 'max_depth': 8}. Best is trial 9 with value: 0.7728119180633147.
[I 2026-08-30 03:41:12,244] Trial 20 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 107, 'max_depth': 12}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-08-30 03:41:12,735] Trial 21 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 139, 'max_depth': 8}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-08-30 03:41:13,095] Trial 22 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 99, 'max_depth': 16}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-08-30 03:41:13,657] Trial 23 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 159, 'max_depth': 14}. Best is trial 20 with value: 0.7802607076350093.
[I 2026-08-30 03:41:14,253] Trial 24 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 182, 'max_depth': 5}. Best is trial 20 with value: 0.7802607076350093.

In [11]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 107, 'max_depth': 12}

In [12]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.75

In [13]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [14]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-08-30 03:41:14,421] A new study created in memory with name: no-name-3aad7eb3-22d4-445e-8c22-8b7176eb26e5
[I 2026-08-30 03:41:14,758] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-08-30 03:41:15,293] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-08-30 03:41:15,484] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-30 03:41:15,845] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-30 03:41:16,202] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-30 03:41:16,387] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-30 03:41:16,882] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-30 03:41:17,413] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-30 03:41:17,940] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-30 03:41:18,647] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-30 03:41:19,360] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-30 03:41:20,081] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-30 03:41:20,752] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-08-30 03:41:20,925] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-08-30 03:41:21,284] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-08-30 03:41:21,473] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [15]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [16]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

### ***Optuna Visualizations***

In [17]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [18]:
# 1. Optimization History
plot_optimization_history(study).show()

In [19]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [20]:
# 3. Slice Plot
plot_slice(study).show()

In [21]:
# 4. Contour Plot
plot_contour(study).show()

In [22]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

### ***Optimizing Multiple ML Models***

In [23]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [24]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [25]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50)

[I 2026-08-30 03:41:23,931] A new study created in memory with name: no-name-60179434-c831-4236-b880-eba2e3222642
[I 2026-08-30 03:41:23,947] Trial 0 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2020347300491629, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 0 with value: 0.7858472998137803.
[I 2026-08-30 03:41:24,401] Trial 1 finished with value: 0.7355679702048418 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 82, 'learning_rate': 0.17170532362616256, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 10}. Best is trial 0 with value: 0.7858472998137803.
[I 2026-08-30 03:41:24,420] Trial 2 finished with value: 0.7616387337057727 and parameters: {'classifier': 'SVM', 'C': 6.5913065357628975, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 0 with value: 0.7858472998137803.
[I 2026-08-30 03:41:25,149] Trial 3 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 239, 'max_depth': 3, 'min_samples_split': 9, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 0 with value: 0.7858472998137803.
[I 2026-08-30 03:41:25,481] Trial 4 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 103, 'max_depth': 18, 'min_samples_split': 4, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 0 with value: 0.7858472998137803.
[I 2026-08-30 03:41:27,041] Trial 5 finished with value: 0.7281191806331471 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 175, 'learning_rate': 0.16935186656969695, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 7}. Best is trial 0 with value: 0.7858472998137803.
[I 2026-08-30 03:41:27,720] Trial 6 finished with value: 0.750465549348231 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 132, 'learning_rate': 0.2791120053663545, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 6}. Best is trial 0 with value: 0.7858472998137803.
[I 2026-08-30 03:41:27,735] Trial 7 finished with value: 0.7262569832402234 and parameters: {'classifier': 'SVM', 'C': 0.33680446512219536, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 0 with value: 0.7858472998137803.
[I 2026-08-30 03:41:27,760] Trial 8 finished with value: 0.7281191806331471 and parameters: {'classifier': 'SVM', 'C': 39.60541565853621, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 0 with value: 0.7858472998137803.
[I 2026-08-30 03:41:27,780] Trial 9 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.494466716632137, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 0 with value: 0.7858472998137803.
[I 2026-08-30 03:41:27,797] Trial 10 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.1998460800355861, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 0 with value: 0.7858472998137803.
[I 2026-08-30 03:41:27,813] Trial 11 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13137724594772582, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:27,828] Trial 12 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11162830427641116, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:27,851] Trial 13 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 0.12778583753976774, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:27,869] Trial 14 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.9070052756297312, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:28,773] Trial 15 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 287, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:28,790] Trial 16 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10440163250370153, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:28,813] Trial 17 finished with value: 0.7467411545623835 and parameters: {'classifier': 'SVM', 'C': 0.6340972317008304, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:29,463] Trial 18 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 199, 'max_depth': 20, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:30,013] Trial 19 finished with value: 0.7318435754189944 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 55, 'learning_rate': 0.013197587634305645, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:30,031] Trial 20 finished with value: 0.7318435754189944 and parameters: {'classifier': 'SVM', 'C': 0.8790088404996885, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:30,047] Trial 21 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10714264215998207, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:30,063] Trial 22 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10707493748775125, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:30,079] Trial 23 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.4010897859513431, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:30,095] Trial 24 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.28747154097561467, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:30,111] Trial 25 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12793763608901948, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:30,128] Trial 26 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.41570802223488273, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:30,147] Trial 27 finished with value: 0.7392923649906891 and parameters: {'classifier': 'SVM', 'C': 2.2693759338805766, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:32,366] Trial 28 finished with value: 0.74487895716946 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 298, 'learning_rate': 0.015397080887339574, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 10}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:32,805] Trial 29 finished with value: 0.7765363128491619 and parameters: {'classifier': 'RandomForest', 'n_estimators': 143, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:32,826] Trial 30 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.20482338860835636, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:32,842] Trial 31 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10171082174717455, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:32,859] Trial 32 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.19296785740359113, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:32,873] Trial 33 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10457838555668462, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:32,889] Trial 34 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2049600115177496, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:32,912] Trial 35 finished with value: 0.750465549348231 and parameters: {'classifier': 'SVM', 'C': 0.5233313442112479, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:37,432] Trial 36 finished with value: 0.7541899441340782 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 232, 'learning_rate': 0.053396046418996264, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:38,255] Trial 37 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 252, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:38,271] Trial 38 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17413211942480522, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:38,287] Trial 39 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2901322145107618, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:40,099] Trial 40 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 181, 'learning_rate': 0.04266689187950672, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 6}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:40,115] Trial 41 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10827554301125207, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:40,131] Trial 42 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14926017343949852, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:40,146] Trial 43 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1552538286820105, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:40,162] Trial 44 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.24571042772488316, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:40,178] Trial 45 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16795644172973612, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:40,211] Trial 46 finished with value: 0.7113594040968342 and parameters: {'classifier': 'SVM', 'C': 93.51379734428157, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:40,383] Trial 47 finished with value: 0.7783985102420856 and parameters: {'classifier': 'RandomForest', 'n_estimators': 55, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:40,399] Trial 48 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.3011737651736278, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 11 with value: 0.7895716945996275.
[I 2026-08-30 03:41:40,417] Trial 49 finished with value: 0.7132216014897579 and parameters: {'classifier': 'SVM', 'C': 0.15420125619601943, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 11 with value: 0.7895716945996275.

In [26]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.13137724594772582, 'kernel': 'linear', 'gamma': 'scale'}
Best trial accuracy: 0.7895716945996275

In [27]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.785847,2026-08-30 03:41:23.932453,2026-08-30 03:41:23.947581,0 days 00:00:00.015128,0.202035,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
1,1,0.735568,2026-08-30 03:41:23.948076,2026-08-30 03:41:24.401926,0 days 00:00:00.453850,NaN,NaN,GradientBoosting,NaN,NaN,0.171705,6.0,10.0,10.0,82.0,COMPLETE
2,2,0.761639,2026-08-30 03:41:24.402539,2026-08-30 03:41:24.420780,0 days 00:00:00.018241,6.591307,NaN,SVM,auto,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
3,3,0.761639,2026-08-30 03:41:24.421261,2026-08-30 03:41:25.149665,0 days 00:00:00.728404,NaN,True,RandomForest,NaN,NaN,NaN,3.0,4.0,9.0,239.0,COMPLETE
4,4,0.767225,2026-08-30 03:41:25.150312,2026-08-30 03:41:25.481656,0 days 00:00:00.331344,NaN,True,RandomForest,NaN,NaN,NaN,18.0,8.0,4.0,103.0,COMPLETE
5,5,0.728119,2026-08-30 03:41:25.482250,2026-08-30 03:41:27.041780,0 days 00:00:01.559530,NaN,NaN,GradientBoosting,NaN,NaN,0.169352,14.0,7.0,2.0,175.0,COMPLETE
6,6,0.750466,2026-08-30 03:41:27.042463,2026-08-30 03:41:27.720469,0 days 00:00:00.678006,NaN,NaN,GradientBoosting,NaN,NaN,0.279112,5.0,6.0,9.0,132.0,COMPLETE
7,7,0.726257,2026-08-30 03:41:27.721061,2026-08-30 03:41:27.735298,0 days 00:00:00.014237,0.336804,NaN,SVM,auto,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
8,8,0.728119,2026-08-30 03:41:27.735724,2026-08-30 03:41:27.760065,0 days 00:00:00.024341,39.605416,NaN,SVM,auto,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
9,9,0.785847,2026-08-30 03:41:27.760625,2026-08-30 03:41:27.780242,0 days 00:00:00.019617,2.494467,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
10,10,0.785847,2026-08-30 03:41:27.780740,2026-08-30 03:41:27.797056,0 days 00:00:00.016316,0.199846,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
11,11,0.789572,2026-08-30 03:41:27.797520,2026-08-30 03:41:27.813077,0 days 00:00:00.015557,0.131377,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
12,12,0.789572,2026-08-30 03:41:27.813502,2026-08-30 03:41:27.828292,0 days 00:00:00.014790,0.111628,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
13,13,0.770950,2026-08-30 03:41:27.828679,2026-08-30 03:41:27.851852,0 days 00:00:00.023173,0.127786,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
14,14,0.785847,2026-08-30 03:41:27.852353,2026-08-30 03:41:27.869085,0 days 00:00:00.016732,0.907005,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
15,15,0.763501,2026-08-30 03:41:27.869505,2026-08-30 03:41:28.773798,0 days 00:00:00.904293,NaN,False,RandomForest,NaN,NaN,NaN,12.0,1.0,6.0,287.0,COMPLETE
16,16,0.787709,2026-08-30 03:41:28.774371,2026-08-30 03:41:28.790308,0 days 00:00:00.015937,0.104402,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
17,17,0.746741,2026-08-30 03:41:28.790776,2026-08-30 03:41:28.813004,0 days 00:00:00.022228,0.634097,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
18,18,0.770950,2026-08-30 03:41:28.813481,2026-08-30 03:41:29.463697,0 days 00:00:00.650216,NaN,False,RandomForest,NaN,NaN,NaN,20.0,1.0,6.0,199.0,COMPLETE
19,19,0.731844,2026-08-30 03:41:29.464641,2026-08-30 03:41:30.013426,0 days 00:00:00.548785,NaN,NaN,GradientBoosting,NaN,NaN,0.013198,9.0,4.0,2.0,55.0,COMPLETE
20,20,0.731844,2026-08-30 03:41:30.014081,2026-08-30 03:41:30.031702,0 days 00:00:00.017621,0.879009,NaN,SVM,scale,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
21,21,0.787709,2026-08-30 03:41:30.032198,2026-08-30 03:41:30.047536,0 days 00:00:00.015338,0.107143,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
22,22,0.787709,2026-08-30 03:41:30.047963,2026-08-30 03:41:30.063403,0 days 00:00:00.015440,0.107075,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
23,23,0.783985,2026-08-30 03:41:30.063771,2026-08-30 03:41:30.079815,0 days 00:00:00.016044,0.401090,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
24,24,0.785847,2026-08-30 03:41:30.080264,2026-08-30 03:41:30.095733,0 days 00:00:00.015469,0.287472,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
25,25,0.789572,2026-08-30 03:41:30.096121,2026-08-30 03:41:30.111518,0 days 00:00:00.015397,0.127938,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
26,26,0.783985,2026-08-30 03:41:30.111877,2026-08-30 03:41:30.128326,0 days 00:00:00.016449,0.415708,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
27,27,0.739292,2026-08-30 03:41:30.128770,2026-08-30 03:41:30.147346,0 days 00:00:00.018576,2.269376,NaN,SVM,scale,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
28,28,0.744879,2026-08-30 03:41:30.147744,2026-08-30 03:41:32.366005,0 days 00:00:02.218261,NaN,NaN,GradientBoosting,NaN,NaN,0.015397,15.0,10.0,7.0,298.0,COMPLETE
29,29,0.776536,2026-08-30 03:41:32.366692,2026-08-30 03:41:32.805293,0 days 00:00:00.438601,NaN,False,RandomForest,NaN,NaN,NaN,9.0,4.0,4.0,143.0,COMPLETE
30,30,0.765363,2026-08-30 03:41:32.805944,2026-08-30 03:41:32.826855,0 days 00:00:00.020911,0.204823,NaN,SVM,scale,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
31,31,0.787709,2026-08-30 03:41:32.827381,2026-08-30 03:41:32.842799,0 days 00:00:00.015418,0.101711,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
32,32,0.785847,2026-08-30 03:41:32.843286,2026-08-30 03:41:32.859074,0 days 00:00:00.015788,0.192968,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
33,33,0.787709,2026-08-30 03:41:32.859503,2026-08-30 03:41:32.873937,0 days 00:00:00.014434,0.104578,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
34,34,0.785847,2026-08-30 03:41:32.874411,2026-08-30 03:41:32.889713,0 days 00:00:00.015302,0.204960,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
35,35,0.750466,2026-08-30 03:41:32.890166,2026-08-30 03:41:32.912934,0 days 00:00:00.022768,0.523331,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
36,36,0.754190,2026-08-30 03:41:32.913411,2026-08-30 03:41:37.432744,0 days 00:00:04.519333,NaN,NaN,GradientBoosting,NaN,NaN,0.053396,17.0,2.0,4.0,232.0,COMPLETE
37,37,0.763501,2026-08-30 03:41:37.433463,2026-08-30 03:41:38.255240,0 days 00:00:00.821777,NaN,True,RandomForest,NaN,NaN,NaN,10.0,8.0,7.0,252.0,COMPLETE
38,38,0.787709,2026-08-30 03:41:38.255904,2026-08-30 03:41:38.271253,0 days 00:00:00.015349,0.174132,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
39,39,0.785847,2026-08-30 03:41:38.271678,2026-08-30 03:41:38.287614,0 days 00:00:00.015936,0.290132,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
40,40,0.741155,2026-08-30 03:41:38.288021,2026-08-30 03:41:40.099415,0 days 00:00:01.811394,NaN,NaN,GradientBoosting,NaN,NaN,0.042667,20.0,6.0,8.0,181.0,COMPLETE
41,41,0.787709,2026-08-30 03:41:40.100000,2026-08-30 03:41:40.115412,0 days 00:00:00.015412,0.108276,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
42,42,0.789572,2026-08-30 03:41:40.115863,2026-08-30 03:41:40.131149,0 days 00:00:00.015286,0.149260,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
43,43,0.787709,2026-08-30 03:41:40.131561,2026-08-30 03:41:40.146627,0 days 00:00:00.015066,0.155254,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
44,44,0.785847,2026-08-30 03:41:40.147025,2026-08-30 03:41:40.162792,0 days 00:00:00.015767,0.245710,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
45,45,0.787709,2026-08-30 03:41:40.163244,2026-08-30 03:41:40.178906,0 days 00:00:00.015662,0.167956,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
46,46,0.711359,2026-08-30 03:41:40.179369,2026-08-30 03:41:40.211605,0 days 00:00:00.032236,93.513797,NaN,SVM,scale,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
47,47,0.778399,2026-08-30 03:41:40.212065,2026-08-30 03:41:40.383681,0 days 00:00:00.171616,NaN,False,RandomForest,NaN,NaN,NaN,6.0,3.0,5.0,55.0,COMPLETE
48,48,0.785847,2026-08-30 03:41:40.384112,2026-08-30 03:41:40.399852,0 days 00:00:00.015740,0.301174,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
49,49,0.713222,2026-08-30 03:41:40.400390,2026-08-30 03:41:40.417397,0 days 00:00:00.017007,0.154201,NaN,SVM,scale,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE

In [28]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 36
GradientBoosting     7
RandomForest         7
Name: count, dtype: int64

In [29]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.740889
RandomForest        0.768821
SVM                 0.772760
Name: value, dtype: float64

In [30]:
# 1. Optimization History
plot_optimization_history(study).show()

In [31]:
# 3. Slice Plot
plot_slice(study).show()

In [32]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

In [38]:
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.13/dist-packages (3.4.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from xgboost) (1.16.3)
Requirement already satisfied: nvidia-nccl-cu13 in /usr/local/lib/python3.13/dist-packages (from xgboost) (2.31.2)

In [39]:
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

# Install xgboost if not already installed
!pip install xgboost
!pip install optuna-integration[xgboost]

# Load the Iris dataset
X, y = load_iris(return_X_y=True)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the objective function for XGBoost
def objective(trial):
    # Hyperparameter search space
    param = {
        'verbosity': 0,
        'objective': 'multi:softprob',
        'num_class': 3,
        'eval_metric': 'mlogloss',  # Ensure that the eval_metric is specified here
        'booster': 'gbtree',
        'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'n_estimators': 300,
    }

    # Create DMatrix for XGBoost
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)

    # Define a pruning callback based on evaluation metrics
    pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss")  # Match the metric name in the evals list

    # Train the model
    bst = xgb.train(
        param,
        dtrain,
        num_boost_round=300,
        evals=[(dtrain, "train"), (dtest, "eval")],  # Ensure the eval datasets and names are specified
        early_stopping_rounds=30,
        callbacks=[pruning_callback]
    )

    # Predict on the test set
    preds = bst.predict(dtest)
    best_preds = [int(np.argmax(line)) for line in preds]

    # Return accuracy as the objective value
    accuracy = accuracy_score(y_test, best_preds)
    return accuracy

# Create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=30)

# Output the best trial
print(f"Best trial: {study.best_trial.params}")
print(f"Best accuracy: {study.best_value}")

Requirement already satisfied: xgboost in /usr/local/lib/python3.13/dist-packages (3.4.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from xgboost) (1.16.3)
Requirement already satisfied: nvidia-nccl-cu13 in /usr/local/lib/python3.13/dist-packages (from xgboost) (2.31.2)
Collecting optuna-integration[xgboost]
  Downloading optuna_integration-4.9.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: optuna in /usr/local/lib/python3.13/dist-packages (from optuna-integration[xgboost]) (4.9.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.13/dist-packages (from optuna-integration[xgboost]) (3.4.1)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (1.19.1)
Requirement already satisfied: colorlog in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (6.12.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (26.3)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.52)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (6.0.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from xgboost->optuna-integration[xgboost]) (1.16.3)
Requirement already satisfied: nvidia-nccl-cu13 in /usr/local/lib/python3.13/dist-packages (from xgboost->optuna-integration[xgboost]) (2.31.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.13/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (4.16.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration[xgboost]) (3.5.5)
Downloading optuna_integration-4.9.0-py3-none-any.whl (103 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.4/103.4 kB 4.7 MB/s eta 0:00:00
Installing collected packages: optuna-integration
Successfully installed optuna-integration-4.9.0

[I 2026-08-30 03:43:14,421] A new study created in memory with name: no-name-b194c55d-8746-4068-8f61-41968daec6f6

[0]	train-mlogloss:1.06617	eval-mlogloss:1.06617
[1]	train-mlogloss:1.02567	eval-mlogloss:1.02288
[2]	train-mlogloss:0.98858	eval-mlogloss:0.98446
[3]	train-mlogloss:0.95663	eval-mlogloss:0.95247
[4]	train-mlogloss:0.92268	eval-mlogloss:0.91676
[5]	train-mlogloss:0.89356	eval-mlogloss:0.88611
[6]	train-mlogloss:0.86656	eval-mlogloss:0.85787
[7]	train-mlogloss:0.84700	eval-mlogloss:0.83788
[8]	train-mlogloss:0.82146	eval-mlogloss:0.81055
[9]	train-mlogloss:0.79425	eval-mlogloss:0.78216
[10]	train-mlogloss:0.76793	eval-mlogloss:0.75335
[11]	train-mlogloss:0.74423	eval-mlogloss:0.72750
[12]	train-mlogloss:0.72521	eval-mlogloss:0.70726
[13]	train-mlogloss:0.70601	eval-mlogloss:0.68782
[14]	train-mlogloss:0.68321	eval-mlogloss:0.66417
[15]	train-mlogloss:0.66305	eval-mlogloss:0.64236
[16]	train-mlogloss:0.64249	eval-mlogloss:0.61976
[17]	train-mlogloss:0.62331	eval-mlogloss:0.59900
[18]	train-mlogloss:0.60470	eval-mlogloss:0.57984
[19]	train-mlogloss:0.58961	eval-mlogloss:0.56438
[20]	train-mlogloss:0.57298	eval-mlogloss:0.54805
[21]	train-mlogloss:0.55628	eval-mlogloss:0.52975
[22]	train-mlogloss:0.54400	eval-mlogloss:0.51632
[23]	train-mlogloss:0.52918	eval-mlogloss:0.50061
[24]	train-mlogloss:0.51446	eval-mlogloss:0.48448
[25]	train-mlogloss:0.49953	eval-mlogloss:0.46895
[26]	train-mlogloss:0.48494	eval-mlogloss:0.45226
[27]	train-mlogloss:0.47115	eval-mlogloss:0.43816
[28]	train-mlogloss:0.45880	eval-mlogloss:0.42514
[29]	train-mlogloss:0.44643	eval-mlogloss:0.41214
[30]	train-mlogloss:0.43661	eval-mlogloss:0.40224
[31]	train-mlogloss:0.42584	eval-mlogloss:0.39062
[32]	train-mlogloss:0.41434	eval-mlogloss:0.37809
[33]	train-mlogloss:0.40838	eval-mlogloss:0.37158
[34]	train-mlogloss:0.39769	eval-mlogloss:0.36071
[35]	train-mlogloss:0.38756	eval-mlogloss:0.35014
[36]	train-mlogloss:0.37809	eval-mlogloss:0.34016
[37]	train-mlogloss:0.36998	eval-mlogloss:0.33049
[38]	train-mlogloss:0.36297	eval-mlogloss:0.32324
[39]	train-mlogloss:0.35375	eval-mlogloss:0.31325
[40]	train-mlogloss:0.34640	eval-mlogloss:0.30581
[41]	train-mlogloss:0.33974	eval-mlogloss:0.29867
[42]	train-mlogloss:0.33355	eval-mlogloss:0.29224
[43]	train-mlogloss:0.32625	eval-mlogloss:0.28365
[44]	train-mlogloss:0.31996	eval-mlogloss:0.27766
[45]	train-mlogloss:0.31399	eval-mlogloss:0.27157
[46]	train-mlogloss:0.30759	eval-mlogloss:0.26556
[47]	train-mlogloss:0.30137	eval-mlogloss:0.25910
[48]	train-mlogloss:0.29463	eval-mlogloss:0.25204
[49]	train-mlogloss:0.28816	eval-mlogloss:0.24451
[50]	train-mlogloss:0.28356	eval-mlogloss:0.23967
[51]	train-mlogloss:0.27737	eval-mlogloss:0.23311
[52]	train-mlogloss:0.27135	eval-mlogloss:0.22656
[53]	train-mlogloss:0.26694	eval-mlogloss:0.22151
[54]	train-mlogloss:0.26144	eval-mlogloss:0.21532
[55]	train-mlogloss:0.25581	eval-mlogloss:0.20878
[56]	train-mlogloss:0.25216	eval-mlogloss:0.20467
[57]	train-mlogloss:0.24922	eval-mlogloss:0.20114
[58]	train-mlogloss:0.24584	eval-mlogloss:0.19740
[59]	train-mlogloss:0.24210	eval-mlogloss:0.19314
[60]	train-mlogloss:0.23830	eval-mlogloss:0.18888
[61]	train-mlogloss:0.23539	eval-mlogloss:0.18589
[62]	train-mlogloss:0.23129	eval-mlogloss:0.18107
[63]	train-mlogloss:0.22806	eval-mlogloss:0.17716
[64]	train-mlogloss:0.22412	eval-mlogloss:0.17279
[65]	train-mlogloss:0.22279	eval-mlogloss:0.17113
[66]	train-mlogloss:0.21996	eval-mlogloss:0.16805
[67]	train-mlogloss:0.21678	eval-mlogloss:0.16431
[68]	train-mlogloss:0.21475	eval-mlogloss:0.16185
[69]	train-mlogloss:0.21233	eval-mlogloss:0.15894
[70]	train-mlogloss:0.21049	eval-mlogloss:0.15725
[71]	train-mlogloss:0.20838	eval-mlogloss:0.15461
[72]	train-mlogloss:0.20521	eval-mlogloss:0.15116
[73]	train-mlogloss:0.20415	eval-mlogloss:0.14983
[74]	train-mlogloss:0.20157	eval-mlogloss:0.14690
[75]	train-mlogloss:0.20093	eval-mlogloss:0.14671
[76]	train-mlogloss:0.19865	eval-mlogloss:0.14423
[77]	train-mlogloss:0.19630	eval-mlogloss:0.14125
[78]	train-mlogloss:0.19506	eval-mlogloss:0.13966
[79]	train-mlogloss:0.19275	eval-mlogloss:0.13689
[80]	train-mlogloss:0.19228	eval-mlogloss:0.13634
[81]	train-mlogloss:0.19215	eval-mlogloss:0.13644
[82]	train-mlogloss:0.19137	eval-mlogloss:0.13540
[83]	train-mlogloss:0.18935	eval-mlogloss:0.13321
[84]	train-mlogloss:0.18850	eval-mlogloss:0.13200
[85]	train-mlogloss:0.18768	eval-mlogloss:0.13080
[86]	train-mlogloss:0.18669	eval-mlogloss:0.12939
[87]	train-mlogloss:0.18640	eval-mlogloss:0.12949
[88]	train-mlogloss:0.18551	eval-mlogloss:0.12837
[89]	train-mlogloss:0.18391	eval-mlogloss:0.12688
[90]	train-mlogloss:0.18281	eval-mlogloss:0.12534
[91]	train-mlogloss:0.18249	eval-mlogloss:0.12514
[92]	train-mlogloss:0.18209	eval-mlogloss:0.12456
[93]	train-mlogloss:0.18118	eval-mlogloss:0.12323
[94]	train-mlogloss:0.18099	eval-mlogloss:0.12299
[95]	train-mlogloss:0.18006	eval-mlogloss:0.12155
[96]	train-mlogloss:0.17910	eval-mlogloss:0.12048
[97]	train-mlogloss:0.17824	eval-mlogloss:0.11934
[98]	train-mlogloss:0.17792	eval-mlogloss:0.11937
[99]	train-mlogloss:0.17774	eval-mlogloss:0.11908
[100]	train-mlogloss:0.17746	eval-mlogloss:0.11864
[101]	train-mlogloss:0.17640	eval-mlogloss:0.11749
[102]	train-mlogloss:0.17628	eval-mlogloss:0.11738
[103]	train-mlogloss:0.17588	eval-mlogloss:0.11673
[104]	train-mlogloss:0.17504	eval-mlogloss:0.11566
[105]	train-mlogloss:0.17349	eval-mlogloss:0.11396
[106]	train-mlogloss:0.17275	eval-mlogloss:0.11254
[107]	train-mlogloss:0.17219	eval-mlogloss:0.11194
[108]	train-mlogloss:0.17205	eval-mlogloss:0.11186
[109]	train-mlogloss:0.17189	eval-mlogloss:0.11156
[110]	train-mlogloss:0.17128	eval-mlogloss:0.11069
[111]	train-mlogloss:0.17113	eval-mlogloss:0.11063
[112]	train-mlogloss:0.17107	eval-mlogloss:0.11055
[113]	train-mlogloss:0.17048	eval-mlogloss:0.10969
[114]	train-mlogloss:0.17003	eval-mlogloss:0.10917
[115]	train-mlogloss:0.16997	eval-mlogloss:0.10911
[116]	train-mlogloss:0.16949	eval-mlogloss:0.10834
[117]	train-mlogloss:0.16889	eval-mlogloss:0.10766
[118]	train-mlogloss:0.16851	eval-mlogloss:0.10713
[119]	train-mlogloss:0.16828	eval-mlogloss:0.10701
[120]	train-mlogloss:0.16811	eval-mlogloss:0.10677
[121]	train-mlogloss:0.16816	eval-mlogloss:0.10682
[122]	train-mlogloss:0.16770	eval-mlogloss:0.10628
[123]	train-mlogloss:0.16775	eval-mlogloss:0.10638
[124]	train-mlogloss:0.16771	eval-mlogloss:0.10634
[125]	train-mlogloss:0.16755	eval-mlogloss:0.10625
[126]	train-mlogloss:0.16750	eval-mlogloss:0.10617
[127]	train-mlogloss:0.16741	eval-mlogloss:0.10627
[128]	train-mlogloss:0.16719	eval-mlogloss:0.10612
[129]	train-mlogloss:0.16704	eval-mlogloss:0.10586
[130]	train-mlogloss:0.16654	eval-mlogloss:0.10520
[131]	train-mlogloss:0.16622	eval-mlogloss:0.10522
[132]	train-mlogloss:0.16566	eval-mlogloss:0.10436
[133]	train-mlogloss:0.16538	eval-mlogloss:0.10424
[134]	train-mlogloss:0.16505	eval-mlogloss:0.10379
[135]	train-mlogloss:0.16495	eval-mlogloss:0.10353
[136]	train-mlogloss:0.16445	eval-mlogloss:0.10300
[137]	train-mlogloss:0.16443	eval-mlogloss:0.10292
[138]	train-mlogloss:0.16414	eval-mlogloss:0.10246
[139]	train-mlogloss:0.16406	eval-mlogloss:0.10231
[140]	train-mlogloss:0.16346	eval-mlogloss:0.10148
[141]	train-mlogloss:0.16316	eval-mlogloss:0.10106
[142]	train-mlogloss:0.16310	eval-mlogloss:0.10104
[143]	train-mlogloss:0.16301	eval-mlogloss:0.10094
[144]	train-mlogloss:0.16267	eval-mlogloss:0.10096
[145]	train-mlogloss:0.16245	eval-mlogloss:0.10087

/usr/lib/python3.13/importlib/__init__.py:88: FutureWarning:

`optuna.integration.xgboost` has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0. Use `optuna_integration.xgboost` instead.

[146]	train-mlogloss:0.16235	eval-mlogloss:0.10081
[147]	train-mlogloss:0.16202	eval-mlogloss:0.10042
[148]	train-mlogloss:0.16162	eval-mlogloss:0.09987
[149]	train-mlogloss:0.16145	eval-mlogloss:0.09955
[150]	train-mlogloss:0.16112	eval-mlogloss:0.09914
[151]	train-mlogloss:0.16099	eval-mlogloss:0.09894
[152]	train-mlogloss:0.16072	eval-mlogloss:0.09887
[153]	train-mlogloss:0.16027	eval-mlogloss:0.09831
[154]	train-mlogloss:0.16025	eval-mlogloss:0.09826
[155]	train-mlogloss:0.16028	eval-mlogloss:0.09833
[156]	train-mlogloss:0.15969	eval-mlogloss:0.09745
[157]	train-mlogloss:0.15969	eval-mlogloss:0.09741
[158]	train-mlogloss:0.15933	eval-mlogloss:0.09745
[159]	train-mlogloss:0.15924	eval-mlogloss:0.09732
[160]	train-mlogloss:0.15922	eval-mlogloss:0.09730
[161]	train-mlogloss:0.15919	eval-mlogloss:0.09723
[162]	train-mlogloss:0.15920	eval-mlogloss:0.09725
[163]	train-mlogloss:0.15907	eval-mlogloss:0.09698
[164]	train-mlogloss:0.15906	eval-mlogloss:0.09699
[165]	train-mlogloss:0.15905	eval-mlogloss:0.09697
[166]	train-mlogloss:0.15905	eval-mlogloss:0.09697
[167]	train-mlogloss:0.15895	eval-mlogloss:0.09684
[168]	train-mlogloss:0.15896	eval-mlogloss:0.09686
[169]	train-mlogloss:0.15891	eval-mlogloss:0.09653
[170]	train-mlogloss:0.15872	eval-mlogloss:0.09646
[171]	train-mlogloss:0.15866	eval-mlogloss:0.09640
[172]	train-mlogloss:0.15817	eval-mlogloss:0.09565
[173]	train-mlogloss:0.15816	eval-mlogloss:0.09564
[174]	train-mlogloss:0.15801	eval-mlogloss:0.09558
[175]	train-mlogloss:0.15782	eval-mlogloss:0.09554
[176]	train-mlogloss:0.15773	eval-mlogloss:0.09542
[177]	train-mlogloss:0.15763	eval-mlogloss:0.09536
[178]	train-mlogloss:0.15758	eval-mlogloss:0.09524
[179]	train-mlogloss:0.15746	eval-mlogloss:0.09507
[180]	train-mlogloss:0.15745	eval-mlogloss:0.09506
[181]	train-mlogloss:0.15745	eval-mlogloss:0.09503
[182]	train-mlogloss:0.15743	eval-mlogloss:0.09472
[183]	train-mlogloss:0.15743	eval-mlogloss:0.09471
[184]	train-mlogloss:0.15733	eval-mlogloss:0.09468
[185]	train-mlogloss:0.15725	eval-mlogloss:0.09447
[186]	train-mlogloss:0.15725	eval-mlogloss:0.09448
[187]	train-mlogloss:0.15725	eval-mlogloss:0.09451
[188]	train-mlogloss:0.15725	eval-mlogloss:0.09452
[189]	train-mlogloss:0.15722	eval-mlogloss:0.09426
[190]	train-mlogloss:0.15710	eval-mlogloss:0.09409
[191]	train-mlogloss:0.15708	eval-mlogloss:0.09404
[192]	train-mlogloss:0.15692	eval-mlogloss:0.09380
[193]	train-mlogloss:0.15689	eval-mlogloss:0.09381
[194]	train-mlogloss:0.15683	eval-mlogloss:0.09381
[195]	train-mlogloss:0.15679	eval-mlogloss:0.09373
[196]	train-mlogloss:0.15658	eval-mlogloss:0.09317
[197]	train-mlogloss:0.15651	eval-mlogloss:0.09303
[198]	train-mlogloss:0.15643	eval-mlogloss:0.09288
[199]	train-mlogloss:0.15623	eval-mlogloss:0.09257
[200]	train-mlogloss:0.15621	eval-mlogloss:0.09256
[201]	train-mlogloss:0.15610	eval-mlogloss:0.09227
[202]	train-mlogloss:0.15612	eval-mlogloss:0.09227
[203]	train-mlogloss:0.15611	eval-mlogloss:0.09226
[204]	train-mlogloss:0.15591	eval-mlogloss:0.09217
[205]	train-mlogloss:0.15591	eval-mlogloss:0.09218
[206]	train-mlogloss:0.15592	eval-mlogloss:0.09219
[207]	train-mlogloss:0.15593	eval-mlogloss:0.09236
[208]	train-mlogloss:0.15591	eval-mlogloss:0.09217
[209]	train-mlogloss:0.15592	eval-mlogloss:0.09220
[210]	train-mlogloss:0.15593	eval-mlogloss:0.09219
[211]	train-mlogloss:0.15594	eval-mlogloss:0.09242
[212]	train-mlogloss:0.15586	eval-mlogloss:0.09252
[213]	train-mlogloss:0.15526	eval-mlogloss:0.09172
[214]	train-mlogloss:0.15528	eval-mlogloss:0.09177
[215]	train-mlogloss:0.15533	eval-mlogloss:0.09184
[216]	train-mlogloss:0.15532	eval-mlogloss:0.09187
[217]	train-mlogloss:0.15513	eval-mlogloss:0.09157
[218]	train-mlogloss:0.15513	eval-mlogloss:0.09166
[219]	train-mlogloss:0.15505	eval-mlogloss:0.09161
[220]	train-mlogloss:0.15506	eval-mlogloss:0.09160
[221]	train-mlogloss:0.15474	eval-mlogloss:0.09107
[222]	train-mlogloss:0.15472	eval-mlogloss:0.09110
[223]	train-mlogloss:0.15463	eval-mlogloss:0.09096
[224]	train-mlogloss:0.15463	eval-mlogloss:0.09101
[225]	train-mlogloss:0.15463	eval-mlogloss:0.09109
[226]	train-mlogloss:0.15461	eval-mlogloss:0.09102
[227]	train-mlogloss:0.15454	eval-mlogloss:0.09097
[228]	train-mlogloss:0.15425	eval-mlogloss:0.09055
[229]	train-mlogloss:0.15426	eval-mlogloss:0.09054
[230]	train-mlogloss:0.15409	eval-mlogloss:0.09026
[231]	train-mlogloss:0.15396	eval-mlogloss:0.09010
[232]	train-mlogloss:0.15393	eval-mlogloss:0.09007
[233]	train-mlogloss:0.15391	eval-mlogloss:0.08997
[234]	train-mlogloss:0.15390	eval-mlogloss:0.08986
[235]	train-mlogloss:0.15369	eval-mlogloss:0.08955
[236]	train-mlogloss:0.15365	eval-mlogloss:0.08924
[237]	train-mlogloss:0.15366	eval-mlogloss:0.08926
[238]	train-mlogloss:0.15344	eval-mlogloss:0.08936
[239]	train-mlogloss:0.15342	eval-mlogloss:0.08933
[240]	train-mlogloss:0.15342	eval-mlogloss:0.08931
[241]	train-mlogloss:0.15334	eval-mlogloss:0.08911
[242]	train-mlogloss:0.15334	eval-mlogloss:0.08914
[243]	train-mlogloss:0.15333	eval-mlogloss:0.08899
[244]	train-mlogloss:0.15334	eval-mlogloss:0.08901
[245]	train-mlogloss:0.15335	eval-mlogloss:0.08906
[246]	train-mlogloss:0.15337	eval-mlogloss:0.08909
[247]	train-mlogloss:0.15333	eval-mlogloss:0.08904
[248]	train-mlogloss:0.15325	eval-mlogloss:0.08890
[249]	train-mlogloss:0.15325	eval-mlogloss:0.08888
[250]	train-mlogloss:0.15326	eval-mlogloss:0.08888
[251]	train-mlogloss:0.15326	eval-mlogloss:0.08891
[252]	train-mlogloss:0.15323	eval-mlogloss:0.08863
[253]	train-mlogloss:0.15323	eval-mlogloss:0.08857
[254]	train-mlogloss:0.15308	eval-mlogloss:0.08851
[255]	train-mlogloss:0.15308	eval-mlogloss:0.08841
[256]	train-mlogloss:0.15302	eval-mlogloss:0.08827
[257]	train-mlogloss:0.15302	eval-mlogloss:0.08828
[258]	train-mlogloss:0.15300	eval-mlogloss:0.08827
[259]	train-mlogloss:0.15296	eval-mlogloss:0.08813
[260]	train-mlogloss:0.15295	eval-mlogloss:0.08810
[261]	train-mlogloss:0.15295	eval-mlogloss:0.08813
[262]	train-mlogloss:0.15288	eval-mlogloss:0.08808
[263]	train-mlogloss:0.15287	eval-mlogloss:0.08817
[264]	train-mlogloss:0.15288	eval-mlogloss:0.08829
[265]	train-mlogloss:0.15287	eval-mlogloss:0.08826
[266]	train-mlogloss:0.15286	eval-mlogloss:0.08826
[267]	train-mlogloss:0.15274	eval-mlogloss:0.08815
[268]	train-mlogloss:0.15276	eval-mlogloss:0.08814
[269]	train-mlogloss:0.15276	eval-mlogloss:0.08813
[270]	train-mlogloss:0.15265	eval-mlogloss:0.08798
[271]	train-mlogloss:0.15264	eval-mlogloss:0.08801
[272]	train-mlogloss:0.15261	eval-mlogloss:0.08779
[273]	train-mlogloss:0.15257	eval-mlogloss:0.08770
[274]	train-mlogloss:0.15244	eval-mlogloss:0.08759
[275]	train-mlogloss:0.15245	eval-mlogloss:0.08757
[276]	train-mlogloss:0.15245	eval-mlogloss:0.08756
[277]	train-mlogloss:0.15244	eval-mlogloss:0.08757
[278]	train-mlogloss:0.15245	eval-mlogloss:0.08753
[279]	train-mlogloss:0.15245	eval-mlogloss:0.08754
[280]	train-mlogloss:0.15244	eval-mlogloss:0.08754
[281]	train-mlogloss:0.15234	eval-mlogloss:0.08751
[282]	train-mlogloss:0.15232	eval-mlogloss:0.08748
[283]	train-mlogloss:0.15213	eval-mlogloss:0.08734
[284]	train-mlogloss:0.15211	eval-mlogloss:0.08727
[285]	train-mlogloss:0.15201	eval-mlogloss:0.08724
[286]	train-mlogloss:0.15201	eval-mlogloss:0.08726
[287]	train-mlogloss:0.15201	eval-mlogloss:0.08729
[288]	train-mlogloss:0.15200	eval-mlogloss:0.08730
[289]	train-mlogloss:0.15149	eval-mlogloss:0.08670
[290]	train-mlogloss:0.15144	eval-mlogloss:0.08666
[291]	train-mlogloss:0.15107	eval-mlogloss:0.08608
[292]	train-mlogloss:0.15103	eval-mlogloss:0.08594
[293]	train-mlogloss:0.15104	eval-mlogloss:0.08592
[294]	train-mlogloss:0.15104	eval-mlogloss:0.08594
[295]	train-mlogloss:0.15098	eval-mlogloss:0.08589
[296]	train-mlogloss:0.15092	eval-mlogloss:0.08583
[297]	train-mlogloss:0.15091	eval-mlogloss:0.08586
[298]	train-mlogloss:0.15090	eval-mlogloss:0.08588
[299]	train-mlogloss:0.15090	eval-mlogloss:0.08589

[I 2026-08-30 03:43:14,826] Trial 0 finished with value: 1.0 and parameters: {'lambda': 3.2246298560619254e-07, 'alpha': 1.316660938476552e-07, 'eta': 0.03196587611314471, 'gamma': 0.0004958214429954585, 'max_depth': 9, 'min_child_weight': 4, 'subsample': 0.5130535342673512, 'colsample_bytree': 0.5601174334707635}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.90307	eval-mlogloss:0.88781
[1]	train-mlogloss:0.71259	eval-mlogloss:0.68728
[2]	train-mlogloss:0.57633	eval-mlogloss:0.53829
[3]	train-mlogloss:0.49582	eval-mlogloss:0.45159
[4]	train-mlogloss:0.42427	eval-mlogloss:0.37589
[5]	train-mlogloss:0.37292	eval-mlogloss:0.32007
[6]	train-mlogloss:0.34067	eval-mlogloss:0.28244
[7]	train-mlogloss:0.31914	eval-mlogloss:0.25662
[8]	train-mlogloss:0.29847	eval-mlogloss:0.23167
[9]	train-mlogloss:0.27445	eval-mlogloss:0.20543
[10]	train-mlogloss:0.27392	eval-mlogloss:0.20482
[11]	train-mlogloss:0.27299	eval-mlogloss:0.20452
[12]	train-mlogloss:0.24903	eval-mlogloss:0.17799
[13]	train-mlogloss:0.24827	eval-mlogloss:0.17750
[14]	train-mlogloss:0.24782	eval-mlogloss:0.17753
[15]	train-mlogloss:0.24738	eval-mlogloss:0.17720
[16]	train-mlogloss:0.24720	eval-mlogloss:0.17724
[17]	train-mlogloss:0.24655	eval-mlogloss:0.17713
[18]	train-mlogloss:0.24636	eval-mlogloss:0.17697
[19]	train-mlogloss:0.24641	eval-mlogloss:0.17670
[20]	train-mlogloss:0.24539	eval-mlogloss:0.17624
[21]	train-mlogloss:0.24020	eval-mlogloss:0.16769
[22]	train-mlogloss:0.24013	eval-mlogloss:0.16829
[23]	train-mlogloss:0.23979	eval-mlogloss:0.16865
[24]	train-mlogloss:0.23973	eval-mlogloss:0.16888
[25]	train-mlogloss:0.23977	eval-mlogloss:0.16913
[26]	train-mlogloss:0.23941	eval-mlogloss:0.16879
[27]	train-mlogloss:0.23919	eval-mlogloss:0.16804
[28]	train-mlogloss:0.23889	eval-mlogloss:0.16797
[29]	train-mlogloss:0.23866	eval-mlogloss:0.16859
[30]	train-mlogloss:0.23857	eval-mlogloss:0.16900
[31]	train-mlogloss:0.23831	eval-mlogloss:0.16847
[32]	train-mlogloss:0.23793	eval-mlogloss:0.16829
[33]	train-mlogloss:0.23800	eval-mlogloss:0.16852
[34]	train-mlogloss:0.23798	eval-mlogloss:0.16835
[35]	train-mlogloss:0.23790	eval-mlogloss:0.16853
[36]	train-mlogloss:0.23769	eval-mlogloss:0.16873
[37]	train-mlogloss:0.23745	eval-mlogloss:0.16761
[38]	train-mlogloss:0.23734	eval-mlogloss:0.16680
[39]	train-mlogloss:0.23678	eval-mlogloss:0.16694
[40]	train-mlogloss:0.23653	eval-mlogloss:0.16812
[41]	train-mlogloss:0.23650	eval-mlogloss:0.16813
[42]	train-mlogloss:0.23621	eval-mlogloss:0.16779
[43]	train-mlogloss:0.23607	eval-mlogloss:0.16715
[44]	train-mlogloss:0.23600	eval-mlogloss:0.16705
[45]	train-mlogloss:0.23604	eval-mlogloss:0.16667
[46]	train-mlogloss:0.23585	eval-mlogloss:0.16662
[47]	train-mlogloss:0.23578	eval-mlogloss:0.16668
[48]	train-mlogloss:0.23561	eval-mlogloss:0.16652
[49]	train-mlogloss:0.23511	eval-mlogloss:0.16584
[50]	train-mlogloss:0.23511	eval-mlogloss:0.16544
[51]	train-mlogloss:0.23512	eval-mlogloss:0.16536
[52]	train-mlogloss:0.23499	eval-mlogloss:0.16520
[53]	train-mlogloss:0.23484	eval-mlogloss:0.16561
[54]	train-mlogloss:0.23479	eval-mlogloss:0.16505
[55]	train-mlogloss:0.23461	eval-mlogloss:0.16512
[56]	train-mlogloss:0.23465	eval-mlogloss:0.16491
[57]	train-mlogloss:0.23460	eval-mlogloss:0.16493
[58]	train-mlogloss:0.23432	eval-mlogloss:0.16485
[59]	train-mlogloss:0.23432	eval-mlogloss:0.16493
[60]	train-mlogloss:0.23418	eval-mlogloss:0.16555
[61]	train-mlogloss:0.23416	eval-mlogloss:0.16591
[62]	train-mlogloss:0.23396	eval-mlogloss:0.16595
[63]	train-mlogloss:0.23372	eval-mlogloss:0.16457
[64]	train-mlogloss:0.23364	eval-mlogloss:0.16386
[65]	train-mlogloss:0.23352	eval-mlogloss:0.16310
[66]	train-mlogloss:0.23355	eval-mlogloss:0.16248
[67]	train-mlogloss:0.23354	eval-mlogloss:0.16268
[68]	train-mlogloss:0.23354	eval-mlogloss:0.16271
[69]	train-mlogloss:0.23351	eval-mlogloss:0.16240
[70]	train-mlogloss:0.23345	eval-mlogloss:0.16193
[71]	train-mlogloss:0.23339	eval-mlogloss:0.16238
[72]	train-mlogloss:0.23332	eval-mlogloss:0.16157
[73]	train-mlogloss:0.23324	eval-mlogloss:0.16143
[74]	train-mlogloss:0.23325	eval-mlogloss:0.16195
[75]	train-mlogloss:0.23320	eval-mlogloss:0.16142
[76]	train-mlogloss:0.23323	eval-mlogloss:0.16117
[77]	train-mlogloss:0.23334	eval-mlogloss:0.16083
[78]	train-mlogloss:0.23341	eval-mlogloss:0.16089
[79]	train-mlogloss:0.23296	eval-mlogloss:0.16050
[80]	train-mlogloss:0.23295	eval-mlogloss:0.16061
[81]	train-mlogloss:0.23296	eval-mlogloss:0.16045
[82]	train-mlogloss:0.23289	eval-mlogloss:0.16014
[83]	train-mlogloss:0.23291	eval-mlogloss:0.15986
[84]	train-mlogloss:0.23290	eval-mlogloss:0.15991
[85]	train-mlogloss:0.23290	eval-mlogloss:0.16001
[86]	train-mlogloss:0.23279	eval-mlogloss:0.15999
[87]	train-mlogloss:0.23287	eval-mlogloss:0.16052
[88]	train-mlogloss:0.23263	eval-mlogloss:0.16078
[89]	train-mlogloss:0.23263	eval-mlogloss:0.16085
[90]	train-mlogloss:0.23251	eval-mlogloss:0.15911
[91]	train-mlogloss:0.23263	eval-mlogloss:0.15841
[92]	train-mlogloss:0.23253	eval-mlogloss:0.15870
[93]	train-mlogloss:0.23259	eval-mlogloss:0.15843
[94]	train-mlogloss:0.23249	eval-mlogloss:0.15887
[95]	train-mlogloss:0.23243	eval-mlogloss:0.15921
[96]	train-mlogloss:0.23244	eval-mlogloss:0.15945
[97]	train-mlogloss:0.23243	eval-mlogloss:0.15979
[98]	train-mlogloss:0.23229	eval-mlogloss:0.15929
[99]	train-mlogloss:0.23226	eval-mlogloss:0.15846
[100]	train-mlogloss:0.23228	eval-mlogloss:0.15834
[101]	train-mlogloss:0.23231	eval-mlogloss:0.15818
[102]	train-mlogloss:0.23237	eval-mlogloss:0.15839
[103]	train-mlogloss:0.23233	eval-mlogloss:0.15898
[104]	train-mlogloss:0.23226	eval-mlogloss:0.15919
[105]	train-mlogloss:0.23220	eval-mlogloss:0.15886
[106]	train-mlogloss:0.23205	eval-mlogloss:0.15887
[107]	train-mlogloss:0.23204	eval-mlogloss:0.15860
[108]	train-mlogloss:0.23202	eval-mlogloss:0.15856
[109]	train-mlogloss:0.23202	eval-mlogloss:0.15863
[110]	train-mlogloss:0.23200	eval-mlogloss:0.15808
[111]	train-mlogloss:0.23203	eval-mlogloss:0.15853
[112]	train-mlogloss:0.23180	eval-mlogloss:0.15796
[113]	train-mlogloss:0.23180	eval-mlogloss:0.15776
[114]	train-mlogloss:0.23179	eval-mlogloss:0.15770
[115]	train-mlogloss:0.23179	eval-mlogloss:0.15764
[116]	train-mlogloss:0.23176	eval-mlogloss:0.15762
[117]	train-mlogloss:0.23180	eval-mlogloss:0.15809
[118]	train-mlogloss:0.23189	eval-mlogloss:0.15860
[119]	train-mlogloss:0.23199	eval-mlogloss:0.15846
[120]	train-mlogloss:0.23204	eval-mlogloss:0.15848
[121]	train-mlogloss:0.23213	eval-mlogloss:0.15908
[122]	train-mlogloss:0.23202	eval-mlogloss:0.15886
[123]	train-mlogloss:0.23178	eval-mlogloss:0.15745
[124]	train-mlogloss:0.23175	eval-mlogloss:0.15715
[125]	train-mlogloss:0.23175	eval-mlogloss:0.15654
[126]	train-mlogloss:0.23175	eval-mlogloss:0.15642
[127]	train-mlogloss:0.23169	eval-mlogloss:0.15717
[128]	train-mlogloss:0.23168	eval-mlogloss:0.15743
[129]	train-mlogloss:0.23168	eval-mlogloss:0.15743
[130]	train-mlogloss:0.23169	eval-mlogloss:0.15744
[131]	train-mlogloss:0.23169	eval-mlogloss:0.15796
[132]	train-mlogloss:0.23162	eval-mlogloss:0.15785
[133]	train-mlogloss:0.23161	eval-mlogloss:0.15761
[134]	train-mlogloss:0.23094	eval-mlogloss:0.15755
[135]	train-mlogloss:0.23099	eval-mlogloss:0.15752
[136]	train-mlogloss:0.23103	eval-mlogloss:0.15791
[137]	train-mlogloss:0.23098	eval-mlogloss:0.15753
[138]	train-mlogloss:0.23098	eval-mlogloss:0.15735
[139]	train-mlogloss:0.23089	eval-mlogloss:0.15785
[140]	train-mlogloss:0.23095	eval-mlogloss:0.15687
[141]	train-mlogloss:0.23097	eval-mlogloss:0.15667
[142]	train-mlogloss:0.23084	eval-mlogloss:0.15721
[143]	train-mlogloss:0.23072	eval-mlogloss:0.15738
[144]	train-mlogloss:0.23072	eval-mlogloss:0.15730
[145]	train-mlogloss:0.23070	eval-mlogloss:0.15726
[146]	train-mlogloss:0.23060	eval-mlogloss:0.15744
[147]	train-mlogloss:0.23056	eval-mlogloss:0.15738
[148]	train-mlogloss:0.23063	eval-mlogloss:0.15802
[149]	train-mlogloss:0.23058	eval-mlogloss:0.15739
[150]	train-mlogloss:0.23055	eval-mlogloss:0.15783
[151]	train-mlogloss:0.23046	eval-mlogloss:0.15717
[152]	train-mlogloss:0.23038	eval-mlogloss:0.15674
[153]	train-mlogloss:0.23047	eval-mlogloss:0.15584
[154]	train-mlogloss:0.23039	eval-mlogloss:0.15670
[155]	train-mlogloss:0.23044	eval-mlogloss:0.15668
[156]	train-mlogloss:0.23046	eval-mlogloss:0.15734
[157]	train-mlogloss:0.23061	eval-mlogloss:0.15798
[158]	train-mlogloss:0.23064	eval-mlogloss:0.15836
[159]	train-mlogloss:0.23052	eval-mlogloss:0.15780
[160]	train-mlogloss:0.23046	eval-mlogloss:0.15736
[161]	train-mlogloss:0.23044	eval-mlogloss:0.15668
[162]	train-mlogloss:0.23044	eval-mlogloss:0.15664
[163]	train-mlogloss:0.23043	eval-mlogloss:0.15656
[164]	train-mlogloss:0.23039	eval-mlogloss:0.15671
[165]	train-mlogloss:0.23022	eval-mlogloss:0.15691
[166]	train-mlogloss:0.23018	eval-mlogloss:0.15670
[167]	train-mlogloss:0.23018	eval-mlogloss:0.15678
[168]	train-mlogloss:0.23027	eval-mlogloss:0.15699
[169]	train-mlogloss:0.23027	eval-mlogloss:0.15690
[170]	train-mlogloss:0.23025	eval-mlogloss:0.15694
[171]	train-mlogloss:0.23025	eval-mlogloss:0.15686
[172]	train-mlogloss:0.23020	eval-mlogloss:0.15692
[173]	train-mlogloss:0.23020	eval-mlogloss:0.15703
[174]	train-mlogloss:0.23023	eval-mlogloss:0.15735
[175]	train-mlogloss:0.23024	eval-mlogloss:0.15725
[176]	train-mlogloss:0.23020	eval-mlogloss:0.15760
[177]	train-mlogloss:0.23019	eval-mlogloss:0.15721
[178]	train-mlogloss:0.23024	eval-mlogloss:0.15683
[179]	train-mlogloss:0.23011	eval-mlogloss:0.15649
[180]	train-mlogloss:0.23015	eval-mlogloss:0.15642
[181]	train-mlogloss:0.23034	eval-mlogloss:0.15617
[182]	train-mlogloss:0.23057	eval-mlogloss:0.15660
[183]	train-mlogloss:0.23028	eval-mlogloss:0.15706

[I 2026-08-30 03:43:15,110] Trial 1 finished with value: 1.0 and parameters: {'lambda': 5.031110577454044e-05, 'alpha': 1.8612003370928783e-06, 'eta': 0.21395395498408576, 'gamma': 2.2793912582212526e-06, 'max_depth': 8, 'min_child_weight': 9, 'subsample': 0.7238387196317639, 'colsample_bytree': 0.6349968957260843}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.98880	eval-mlogloss:0.98412
[1]	train-mlogloss:0.87289	eval-mlogloss:0.86272
[2]	train-mlogloss:0.77743	eval-mlogloss:0.75952
[3]	train-mlogloss:0.70306	eval-mlogloss:0.68372
[4]	train-mlogloss:0.63090	eval-mlogloss:0.60798
[5]	train-mlogloss:0.57537	eval-mlogloss:0.55236
[6]	train-mlogloss:0.52647	eval-mlogloss:0.50429
[7]	train-mlogloss:0.49576	eval-mlogloss:0.47322
[8]	train-mlogloss:0.45749	eval-mlogloss:0.43316
[9]	train-mlogloss:0.41709	eval-mlogloss:0.38962
[10]	train-mlogloss:0.38228	eval-mlogloss:0.35169
[11]	train-mlogloss:0.35231	eval-mlogloss:0.31927
[12]	train-mlogloss:0.33113	eval-mlogloss:0.29840
[13]	train-mlogloss:0.31255	eval-mlogloss:0.27693
[14]	train-mlogloss:0.28897	eval-mlogloss:0.25170
[15]	train-mlogloss:0.27010	eval-mlogloss:0.23041
[16]	train-mlogloss:0.25440	eval-mlogloss:0.21176
[17]	train-mlogloss:0.23852	eval-mlogloss:0.19390
[18]	train-mlogloss:0.22594	eval-mlogloss:0.17926
[19]	train-mlogloss:0.21622	eval-mlogloss:0.16905
[20]	train-mlogloss:0.20618	eval-mlogloss:0.15695
[21]	train-mlogloss:0.19794	eval-mlogloss:0.14704
[22]	train-mlogloss:0.19119	eval-mlogloss:0.13849
[23]	train-mlogloss:0.18392	eval-mlogloss:0.13033
[24]	train-mlogloss:0.18182	eval-mlogloss:0.12723
[25]	train-mlogloss:0.17856	eval-mlogloss:0.12353
[26]	train-mlogloss:0.17622	eval-mlogloss:0.12106
[27]	train-mlogloss:0.17363	eval-mlogloss:0.11759
[28]	train-mlogloss:0.17206	eval-mlogloss:0.11539
[29]	train-mlogloss:0.17066	eval-mlogloss:0.11335
[30]	train-mlogloss:0.16984	eval-mlogloss:0.11356
[31]	train-mlogloss:0.16781	eval-mlogloss:0.11066

[I 2026-08-30 03:43:15,139] Trial 2 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:0.84733	eval-mlogloss:0.83354
[1]	train-mlogloss:0.62886	eval-mlogloss:0.60281

[I 2026-08-30 03:43:15,143] Trial 3 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.02032	eval-mlogloss:1.01470
[1]	train-mlogloss:0.93131	eval-mlogloss:0.91958
[2]	train-mlogloss:0.84934	eval-mlogloss:0.83088
[3]	train-mlogloss:0.78888	eval-mlogloss:0.76764
[4]	train-mlogloss:0.72604	eval-mlogloss:0.70308
[5]	train-mlogloss:0.67472	eval-mlogloss:0.64816
[6]	train-mlogloss:0.63183	eval-mlogloss:0.60650
[7]	train-mlogloss:0.60576	eval-mlogloss:0.57741
[8]	train-mlogloss:0.58082	eval-mlogloss:0.54501
[9]	train-mlogloss:0.55080	eval-mlogloss:0.51107
[10]	train-mlogloss:0.52370	eval-mlogloss:0.48127
[11]	train-mlogloss:0.49352	eval-mlogloss:0.44716
[12]	train-mlogloss:0.46756	eval-mlogloss:0.42120
[13]	train-mlogloss:0.44776	eval-mlogloss:0.40205
[14]	train-mlogloss:0.42754	eval-mlogloss:0.38054
[15]	train-mlogloss:0.40879	eval-mlogloss:0.35971
[16]	train-mlogloss:0.39214	eval-mlogloss:0.34109
[17]	train-mlogloss:0.38493	eval-mlogloss:0.33218
[18]	train-mlogloss:0.36969	eval-mlogloss:0.31665
[19]	train-mlogloss:0.35900	eval-mlogloss:0.30429
[20]	train-mlogloss:0.35756	eval-mlogloss:0.30230
[21]	train-mlogloss:0.34478	eval-mlogloss:0.28789
[22]	train-mlogloss:0.33980	eval-mlogloss:0.28192
[23]	train-mlogloss:0.33887	eval-mlogloss:0.28141
[24]	train-mlogloss:0.33491	eval-mlogloss:0.27684
[25]	train-mlogloss:0.33404	eval-mlogloss:0.27649
[26]	train-mlogloss:0.32698	eval-mlogloss:0.26976
[27]	train-mlogloss:0.32660	eval-mlogloss:0.26885
[28]	train-mlogloss:0.32246	eval-mlogloss:0.26435
[29]	train-mlogloss:0.32188	eval-mlogloss:0.26409
[30]	train-mlogloss:0.32056	eval-mlogloss:0.26302
[31]	train-mlogloss:0.32022	eval-mlogloss:0.26275
[32]	train-mlogloss:0.31590	eval-mlogloss:0.25777
[33]	train-mlogloss:0.31607	eval-mlogloss:0.25792
[34]	train-mlogloss:0.31587	eval-mlogloss:0.25760
[35]	train-mlogloss:0.31139	eval-mlogloss:0.25139
[36]	train-mlogloss:0.31125	eval-mlogloss:0.25163
[37]	train-mlogloss:0.31093	eval-mlogloss:0.25134
[38]	train-mlogloss:0.31060	eval-mlogloss:0.25042
[39]	train-mlogloss:0.31021	eval-mlogloss:0.25030
[40]	train-mlogloss:0.30700	eval-mlogloss:0.24675
[41]	train-mlogloss:0.30691	eval-mlogloss:0.24677
[42]	train-mlogloss:0.30651	eval-mlogloss:0.24655
[43]	train-mlogloss:0.30629	eval-mlogloss:0.24643
[44]	train-mlogloss:0.30600	eval-mlogloss:0.24613
[45]	train-mlogloss:0.30600	eval-mlogloss:0.24625
[46]	train-mlogloss:0.30592	eval-mlogloss:0.24615
[47]	train-mlogloss:0.30587	eval-mlogloss:0.24610
[48]	train-mlogloss:0.30543	eval-mlogloss:0.24470
[49]	train-mlogloss:0.30496	eval-mlogloss:0.24432
[50]	train-mlogloss:0.30480	eval-mlogloss:0.24410
[51]	train-mlogloss:0.30474	eval-mlogloss:0.24418
[52]	train-mlogloss:0.30335	eval-mlogloss:0.24281
[53]	train-mlogloss:0.30339	eval-mlogloss:0.24294
[54]	train-mlogloss:0.30307	eval-mlogloss:0.24193
[55]	train-mlogloss:0.30303	eval-mlogloss:0.24183
[56]	train-mlogloss:0.30305	eval-mlogloss:0.24178
[57]	train-mlogloss:0.30287	eval-mlogloss:0.24163
[58]	train-mlogloss:0.30258	eval-mlogloss:0.24146
[59]	train-mlogloss:0.29820	eval-mlogloss:0.23592
[60]	train-mlogloss:0.29780	eval-mlogloss:0.23486
[61]	train-mlogloss:0.29749	eval-mlogloss:0.23479
[62]	train-mlogloss:0.29723	eval-mlogloss:0.23460
[63]	train-mlogloss:0.29686	eval-mlogloss:0.23361
[64]	train-mlogloss:0.29661	eval-mlogloss:0.23281
[65]	train-mlogloss:0.29643	eval-mlogloss:0.23255
[66]	train-mlogloss:0.29629	eval-mlogloss:0.23272
[67]	train-mlogloss:0.29629	eval-mlogloss:0.23269
[68]	train-mlogloss:0.29631	eval-mlogloss:0.23280
[69]	train-mlogloss:0.29619	eval-mlogloss:0.23266
[70]	train-mlogloss:0.29603	eval-mlogloss:0.23253
[71]	train-mlogloss:0.29580	eval-mlogloss:0.23251
[72]	train-mlogloss:0.29548	eval-mlogloss:0.23167
[73]	train-mlogloss:0.29551	eval-mlogloss:0.23159
[74]	train-mlogloss:0.29544	eval-mlogloss:0.23156
[75]	train-mlogloss:0.29501	eval-mlogloss:0.23008
[76]	train-mlogloss:0.29500	eval-mlogloss:0.22998
[77]	train-mlogloss:0.29467	eval-mlogloss:0.22966
[78]	train-mlogloss:0.29437	eval-mlogloss:0.22932
[79]	train-mlogloss:0.29399	eval-mlogloss:0.22818
[80]	train-mlogloss:0.29398	eval-mlogloss:0.22826
[81]	train-mlogloss:0.29399	eval-mlogloss:0.22824
[82]	train-mlogloss:0.29375	eval-mlogloss:0.22745
[83]	train-mlogloss:0.29357	eval-mlogloss:0.22768
[84]	train-mlogloss:0.29356	eval-mlogloss:0.22765
[85]	train-mlogloss:0.29338	eval-mlogloss:0.22747
[86]	train-mlogloss:0.29330	eval-mlogloss:0.22736
[87]	train-mlogloss:0.29326	eval-mlogloss:0.22729
[88]	train-mlogloss:0.29317	eval-mlogloss:0.22741
[89]	train-mlogloss:0.29316	eval-mlogloss:0.22745
[90]	train-mlogloss:0.29284	eval-mlogloss:0.22627
[91]	train-mlogloss:0.29290	eval-mlogloss:0.22613
[92]	train-mlogloss:0.29284	eval-mlogloss:0.22633
[93]	train-mlogloss:0.29265	eval-mlogloss:0.22609
[94]	train-mlogloss:0.29260	eval-mlogloss:0.22625
[95]	train-mlogloss:0.29244	eval-mlogloss:0.22578
[96]	train-mlogloss:0.29243	eval-mlogloss:0.22592
[97]	train-mlogloss:0.29222	eval-mlogloss:0.22572
[98]	train-mlogloss:0.29200	eval-mlogloss:0.22554
[99]	train-mlogloss:0.29189	eval-mlogloss:0.22563
[100]	train-mlogloss:0.29167	eval-mlogloss:0.22549
[101]	train-mlogloss:0.29168	eval-mlogloss:0.22546
[102]	train-mlogloss:0.29154	eval-mlogloss:0.22526
[103]	train-mlogloss:0.29149	eval-mlogloss:0.22552
[104]	train-mlogloss:0.29139	eval-mlogloss:0.22538
[105]	train-mlogloss:0.29104	eval-mlogloss:0.22478
[106]	train-mlogloss:0.29084	eval-mlogloss:0.22464
[107]	train-mlogloss:0.29086	eval-mlogloss:0.22452
[108]	train-mlogloss:0.29086	eval-mlogloss:0.22447
[109]	train-mlogloss:0.29075	eval-mlogloss:0.22435
[110]	train-mlogloss:0.29074	eval-mlogloss:0.22440
[111]	train-mlogloss:0.29066	eval-mlogloss:0.22471
[112]	train-mlogloss:0.29035	eval-mlogloss:0.22446
[113]	train-mlogloss:0.29035	eval-mlogloss:0.22441
[114]	train-mlogloss:0.29026	eval-mlogloss:0.22435
[115]	train-mlogloss:0.29012	eval-mlogloss:0.22383
[116]	train-mlogloss:0.29005	eval-mlogloss:0.22379
[117]	train-mlogloss:0.28987	eval-mlogloss:0.22384
[118]	train-mlogloss:0.28998	eval-mlogloss:0.22380
[119]	train-mlogloss:0.28979	eval-mlogloss:0.22382
[120]	train-mlogloss:0.28969	eval-mlogloss:0.22388
[121]	train-mlogloss:0.28971	eval-mlogloss:0.22404
[122]	train-mlogloss:0.28968	eval-mlogloss:0.22392
[123]	train-mlogloss:0.28952	eval-mlogloss:0.22338
[124]	train-mlogloss:0.28953	eval-mlogloss:0.22340
[125]	train-mlogloss:0.28936	eval-mlogloss:0.22335
[126]	train-mlogloss:0.28926	eval-mlogloss:0.22312
[127]	train-mlogloss:0.28924	eval-mlogloss:0.22320
[128]	train-mlogloss:0.28922	eval-mlogloss:0.22314
[129]	train-mlogloss:0.28922	eval-mlogloss:0.22308
[130]	train-mlogloss:0.28914	eval-mlogloss:0.22299
[131]	train-mlogloss:0.28891	eval-mlogloss:0.22207
[132]	train-mlogloss:0.28866	eval-mlogloss:0.22180
[133]	train-mlogloss:0.28861	eval-mlogloss:0.22189
[134]	train-mlogloss:0.28807	eval-mlogloss:0.22171
[135]	train-mlogloss:0.28810	eval-mlogloss:0.22164
[136]	train-mlogloss:0.28802	eval-mlogloss:0.22169
[137]	train-mlogloss:0.28801	eval-mlogloss:0.22166
[138]	train-mlogloss:0.28803	eval-mlogloss:0.22153
[139]	train-mlogloss:0.28797	eval-mlogloss:0.22179
[140]	train-mlogloss:0.28800	eval-mlogloss:0.22148
[141]	train-mlogloss:0.28801	eval-mlogloss:0.22138
[142]	train-mlogloss:0.28797	eval-mlogloss:0.22163
[143]	train-mlogloss:0.28784	eval-mlogloss:0.22121
[144]	train-mlogloss:0.28784	eval-mlogloss:0.22121
[145]	train-mlogloss:0.28775	eval-mlogloss:0.22109
[146]	train-mlogloss:0.28775	eval-mlogloss:0.22118
[147]	train-mlogloss:0.28374	eval-mlogloss:0.21656
[148]	train-mlogloss:0.28374	eval-mlogloss:0.21673
[149]	train-mlogloss:0.28362	eval-mlogloss:0.21656
[150]	train-mlogloss:0.28349	eval-mlogloss:0.21660
[151]	train-mlogloss:0.28348	eval-mlogloss:0.21649
[152]	train-mlogloss:0.28336	eval-mlogloss:0.21645
[153]	train-mlogloss:0.28337	eval-mlogloss:0.21620
[154]	train-mlogloss:0.28336	eval-mlogloss:0.21614
[155]	train-mlogloss:0.28337	eval-mlogloss:0.21607
[156]	train-mlogloss:0.28101	eval-mlogloss:0.21313
[157]	train-mlogloss:0.28103	eval-mlogloss:0.21335
[158]	train-mlogloss:0.28104	eval-mlogloss:0.21348
[159]	train-mlogloss:0.28092	eval-mlogloss:0.21357
[160]	train-mlogloss:0.28080	eval-mlogloss:0.21334
[161]	train-mlogloss:0.28080	eval-mlogloss:0.21317
[162]	train-mlogloss:0.28081	eval-mlogloss:0.21317
[163]	train-mlogloss:0.28075	eval-mlogloss:0.21330
[164]	train-mlogloss:0.28074	eval-mlogloss:0.21320
[165]	train-mlogloss:0.28067	eval-mlogloss:0.21339
[166]	train-mlogloss:0.28060	eval-mlogloss:0.21312
[167]	train-mlogloss:0.28060	eval-mlogloss:0.21312
[168]	train-mlogloss:0.28063	eval-mlogloss:0.21304
[169]	train-mlogloss:0.28063	eval-mlogloss:0.21298
[170]	train-mlogloss:0.28060	eval-mlogloss:0.21309
[171]	train-mlogloss:0.28055	eval-mlogloss:0.21290
[172]	train-mlogloss:0.28046	eval-mlogloss:0.21235
[173]	train-mlogloss:0.28046	eval-mlogloss:0.21234
[174]	train-mlogloss:0.28032	eval-mlogloss:0.21229
[175]	train-mlogloss:0.28033	eval-mlogloss:0.21224
[176]	train-mlogloss:0.28031	eval-mlogloss:0.21247
[177]	train-mlogloss:0.28028	eval-mlogloss:0.21229
[178]	train-mlogloss:0.28027	eval-mlogloss:0.21214
[179]	train-mlogloss:0.28017	eval-mlogloss:0.21202
[180]	train-mlogloss:0.28017	eval-mlogloss:0.21200
[181]	train-mlogloss:0.28021	eval-mlogloss:0.21183
[182]	train-mlogloss:0.28020	eval-mlogloss:0.21117
[183]	train-mlogloss:0.28015	eval-mlogloss:0.21128
[184]	train-mlogloss:0.28006	eval-mlogloss:0.21130
[185]	train-mlogloss:0.28010	eval-mlogloss:0.21119
[186]	train-mlogloss:0.28005	eval-mlogloss:0.21137
[187]	train-mlogloss:0.27999	eval-mlogloss:0.21141
[188]	train-mlogloss:0.28000	eval-mlogloss:0.21126
[189]	train-mlogloss:0.27982	eval-mlogloss:0.21016
[190]	train-mlogloss:0.27986	eval-mlogloss:0.21003
[191]	train-mlogloss:0.27980	eval-mlogloss:0.21013
[192]	train-mlogloss:0.27980	eval-mlogloss:0.21013
[193]	train-mlogloss:0.27978	eval-mlogloss:0.21019
[194]	train-mlogloss:0.27967	eval-mlogloss:0.20983
[195]	train-mlogloss:0.27964	eval-mlogloss:0.20991
[196]	train-mlogloss:0.27965	eval-mlogloss:0.20986
[197]	train-mlogloss:0.27965	eval-mlogloss:0.20990
[198]	train-mlogloss:0.27963	eval-mlogloss:0.20990
[199]	train-mlogloss:0.27959	eval-mlogloss:0.21011
[200]	train-mlogloss:0.27956	eval-mlogloss:0.21014
[201]	train-mlogloss:0.27958	eval-mlogloss:0.21010
[202]	train-mlogloss:0.27961	eval-mlogloss:0.21024
[203]	train-mlogloss:0.27954	eval-mlogloss:0.21047
[204]	train-mlogloss:0.27946	eval-mlogloss:0.21034
[205]	train-mlogloss:0.27943	eval-mlogloss:0.21036
[206]	train-mlogloss:0.27954	eval-mlogloss:0.21054
[207]	train-mlogloss:0.27951	eval-mlogloss:0.21041
[208]	train-mlogloss:0.27949	eval-mlogloss:0.21054
[209]	train-mlogloss:0.27947	eval-mlogloss:0.21052
[210]	train-mlogloss:0.27952	eval-mlogloss:0.21071
[211]	train-mlogloss:0.27949	eval-mlogloss:0.21075
[212]	train-mlogloss:0.27943	eval-mlogloss:0.21092
[213]	train-mlogloss:0.27933	eval-mlogloss:0.21093
[214]	train-mlogloss:0.27938	eval-mlogloss:0.21110
[215]	train-mlogloss:0.27935	eval-mlogloss:0.21095
[216]	train-mlogloss:0.27932	eval-mlogloss:0.21090
[217]	train-mlogloss:0.27928	eval-mlogloss:0.21074
[218]	train-mlogloss:0.27926	eval-mlogloss:0.21080
[219]	train-mlogloss:0.27925	eval-mlogloss:0.21078
[220]	train-mlogloss:0.27924	eval-mlogloss:0.21070
[221]	train-mlogloss:0.27925	eval-mlogloss:0.21077
[222]	train-mlogloss:0.27923	eval-mlogloss:0.21081
[223]	train-mlogloss:0.27923	eval-mlogloss:0.21095
[224]	train-mlogloss:0.27926	eval-mlogloss:0.21096

[I 2026-08-30 03:43:15,494] Trial 4 finished with value: 1.0 and parameters: {'lambda': 1.3005898164406863e-08, 'alpha': 0.001904208139895962, 'eta': 0.08231318438264908, 'gamma': 0.010477722683736486, 'max_depth': 6, 'min_child_weight': 10, 'subsample': 0.6721343383862132, 'colsample_bytree': 0.6532673176957845}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.98510	eval-mlogloss:0.97913
[1]	train-mlogloss:0.88751	eval-mlogloss:0.87699

[I 2026-08-30 03:43:15,500] Trial 5 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.88235	eval-mlogloss:0.88837
[1]	train-mlogloss:0.69614	eval-mlogloss:0.68717

[I 2026-08-30 03:43:15,504] Trial 6 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.78111	eval-mlogloss:0.76281
[1]	train-mlogloss:0.58666	eval-mlogloss:0.55597

[I 2026-08-30 03:43:15,508] Trial 7 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.89523	eval-mlogloss:0.88079
[1]	train-mlogloss:0.73865	eval-mlogloss:0.71102

[I 2026-08-30 03:43:15,512] Trial 8 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.87595	eval-mlogloss:0.86850
[1]	train-mlogloss:0.71549	eval-mlogloss:0.69792

[I 2026-08-30 03:43:15,516] Trial 9 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.07457	eval-mlogloss:1.07749
[1]	train-mlogloss:1.04917	eval-mlogloss:1.05138
[2]	train-mlogloss:1.03784	eval-mlogloss:1.04398
[3]	train-mlogloss:1.02578	eval-mlogloss:1.03336
[4]	train-mlogloss:1.00240	eval-mlogloss:1.00997
[5]	train-mlogloss:0.97635	eval-mlogloss:0.98259
[6]	train-mlogloss:0.96636	eval-mlogloss:0.97296
[7]	train-mlogloss:0.95468	eval-mlogloss:0.96056
[8]	train-mlogloss:0.93386	eval-mlogloss:0.93843
[9]	train-mlogloss:0.91125	eval-mlogloss:0.91494
[10]	train-mlogloss:0.89381	eval-mlogloss:0.89414
[11]	train-mlogloss:0.87576	eval-mlogloss:0.87470
[12]	train-mlogloss:0.85772	eval-mlogloss:0.85475
[13]	train-mlogloss:0.84442	eval-mlogloss:0.84214
[14]	train-mlogloss:0.82688	eval-mlogloss:0.82400
[15]	train-mlogloss:0.81073	eval-mlogloss:0.80816
[16]	train-mlogloss:0.79501	eval-mlogloss:0.79169
[17]	train-mlogloss:0.77522	eval-mlogloss:0.76998
[18]	train-mlogloss:0.75982	eval-mlogloss:0.75392
[19]	train-mlogloss:0.74480	eval-mlogloss:0.73872
[20]	train-mlogloss:0.73562	eval-mlogloss:0.73067
[21]	train-mlogloss:0.71973	eval-mlogloss:0.71503
[22]	train-mlogloss:0.70719	eval-mlogloss:0.70117
[23]	train-mlogloss:0.70210	eval-mlogloss:0.69636
[24]	train-mlogloss:0.68538	eval-mlogloss:0.67788
[25]	train-mlogloss:0.66878	eval-mlogloss:0.66050
[26]	train-mlogloss:0.65868	eval-mlogloss:0.64928
[27]	train-mlogloss:0.65282	eval-mlogloss:0.64358
[28]	train-mlogloss:0.64374	eval-mlogloss:0.63446
[29]	train-mlogloss:0.63133	eval-mlogloss:0.62089
[30]	train-mlogloss:0.62473	eval-mlogloss:0.61550
[31]	train-mlogloss:0.61435	eval-mlogloss:0.60439
[32]	train-mlogloss:0.60276	eval-mlogloss:0.59145
[33]	train-mlogloss:0.59859	eval-mlogloss:0.58729
[34]	train-mlogloss:0.58469	eval-mlogloss:0.57242
[35]	train-mlogloss:0.57469	eval-mlogloss:0.56218
[36]	train-mlogloss:0.56471	eval-mlogloss:0.55183
[37]	train-mlogloss:0.55914	eval-mlogloss:0.54591
[38]	train-mlogloss:0.55329	eval-mlogloss:0.54021
[39]	train-mlogloss:0.54872	eval-mlogloss:0.53545
[40]	train-mlogloss:0.54122	eval-mlogloss:0.52760
[41]	train-mlogloss:0.53452	eval-mlogloss:0.52045
[42]	train-mlogloss:0.52614	eval-mlogloss:0.51186
[43]	train-mlogloss:0.51986	eval-mlogloss:0.50533
[44]	train-mlogloss:0.51172	eval-mlogloss:0.49694
[45]	train-mlogloss:0.50108	eval-mlogloss:0.48501
[46]	train-mlogloss:0.49574	eval-mlogloss:0.47922
[47]	train-mlogloss:0.48772	eval-mlogloss:0.47004
[48]	train-mlogloss:0.48171	eval-mlogloss:0.46285
[49]	train-mlogloss:0.47774	eval-mlogloss:0.45882
[50]	train-mlogloss:0.47328	eval-mlogloss:0.45424
[51]	train-mlogloss:0.46647	eval-mlogloss:0.44743
[52]	train-mlogloss:0.45693	eval-mlogloss:0.43662
[53]	train-mlogloss:0.45075	eval-mlogloss:0.43034
[54]	train-mlogloss:0.44163	eval-mlogloss:0.42005
[55]	train-mlogloss:0.43471	eval-mlogloss:0.41234
[56]	train-mlogloss:0.42838	eval-mlogloss:0.40614
[57]	train-mlogloss:0.42601	eval-mlogloss:0.40446
[58]	train-mlogloss:0.42399	eval-mlogloss:0.40323
[59]	train-mlogloss:0.41645	eval-mlogloss:0.39506
[60]	train-mlogloss:0.41152	eval-mlogloss:0.38906
[61]	train-mlogloss:0.40789	eval-mlogloss:0.38565
[62]	train-mlogloss:0.40239	eval-mlogloss:0.38043
[63]	train-mlogloss:0.39921	eval-mlogloss:0.37775
[64]	train-mlogloss:0.39665	eval-mlogloss:0.37428
[65]	train-mlogloss:0.39518	eval-mlogloss:0.37353
[66]	train-mlogloss:0.38761	eval-mlogloss:0.36531
[67]	train-mlogloss:0.38410	eval-mlogloss:0.36285
[68]	train-mlogloss:0.38054	eval-mlogloss:0.35946
[69]	train-mlogloss:0.37505	eval-mlogloss:0.35372
[70]	train-mlogloss:0.37209	eval-mlogloss:0.35088
[71]	train-mlogloss:0.36711	eval-mlogloss:0.34567
[72]	train-mlogloss:0.36116	eval-mlogloss:0.33951
[73]	train-mlogloss:0.36008	eval-mlogloss:0.33883
[74]	train-mlogloss:0.35485	eval-mlogloss:0.33338
[75]	train-mlogloss:0.35297	eval-mlogloss:0.33199
[76]	train-mlogloss:0.34809	eval-mlogloss:0.32667
[77]	train-mlogloss:0.34666	eval-mlogloss:0.32511
[78]	train-mlogloss:0.34260	eval-mlogloss:0.32031
[79]	train-mlogloss:0.33757	eval-mlogloss:0.31425
[80]	train-mlogloss:0.33618	eval-mlogloss:0.31300
[81]	train-mlogloss:0.33235	eval-mlogloss:0.30927
[82]	train-mlogloss:0.33109	eval-mlogloss:0.30866
[83]	train-mlogloss:0.32630	eval-mlogloss:0.30379
[84]	train-mlogloss:0.32477	eval-mlogloss:0.30258
[85]	train-mlogloss:0.31902	eval-mlogloss:0.29596
[86]	train-mlogloss:0.31623	eval-mlogloss:0.29390
[87]	train-mlogloss:0.31286	eval-mlogloss:0.29025
[88]	train-mlogloss:0.30917	eval-mlogloss:0.28679
[89]	train-mlogloss:0.30702	eval-mlogloss:0.28448
[90]	train-mlogloss:0.30284	eval-mlogloss:0.28008
[91]	train-mlogloss:0.30106	eval-mlogloss:0.27828
[92]	train-mlogloss:0.29703	eval-mlogloss:0.27362
[93]	train-mlogloss:0.29381	eval-mlogloss:0.27038
[94]	train-mlogloss:0.29156	eval-mlogloss:0.26776
[95]	train-mlogloss:0.28762	eval-mlogloss:0.26259
[96]	train-mlogloss:0.28568	eval-mlogloss:0.26005
[97]	train-mlogloss:0.28131	eval-mlogloss:0.25524
[98]	train-mlogloss:0.28011	eval-mlogloss:0.25442
[99]	train-mlogloss:0.27717	eval-mlogloss:0.25120
[100]	train-mlogloss:0.27626	eval-mlogloss:0.25033
[101]	train-mlogloss:0.27538	eval-mlogloss:0.25010
[102]	train-mlogloss:0.27198	eval-mlogloss:0.24640
[103]	train-mlogloss:0.26904	eval-mlogloss:0.24335
[104]	train-mlogloss:0.26680	eval-mlogloss:0.24099
[105]	train-mlogloss:0.26285	eval-mlogloss:0.23641
[106]	train-mlogloss:0.26139	eval-mlogloss:0.23506
[107]	train-mlogloss:0.25979	eval-mlogloss:0.23336
[108]	train-mlogloss:0.25730	eval-mlogloss:0.23048
[109]	train-mlogloss:0.25435	eval-mlogloss:0.22745
[110]	train-mlogloss:0.25264	eval-mlogloss:0.22558
[111]	train-mlogloss:0.25118	eval-mlogloss:0.22430
[112]	train-mlogloss:0.24834	eval-mlogloss:0.22149
[113]	train-mlogloss:0.24799	eval-mlogloss:0.22130
[114]	train-mlogloss:0.24571	eval-mlogloss:0.21850
[115]	train-mlogloss:0.24216	eval-mlogloss:0.21450
[116]	train-mlogloss:0.24057	eval-mlogloss:0.21312
[117]	train-mlogloss:0.23809	eval-mlogloss:0.21035
[118]	train-mlogloss:0.23580	eval-mlogloss:0.20822
[119]	train-mlogloss:0.23308	eval-mlogloss:0.20494
[120]	train-mlogloss:0.23023	eval-mlogloss:0.20174
[121]	train-mlogloss:0.22836	eval-mlogloss:0.19925
[122]	train-mlogloss:0.22506	eval-mlogloss:0.19563
[123]	train-mlogloss:0.22360	eval-mlogloss:0.19369
[124]	train-mlogloss:0.22207	eval-mlogloss:0.19198
[125]	train-mlogloss:0.21949	eval-mlogloss:0.18957
[126]	train-mlogloss:0.21840	eval-mlogloss:0.18859
[127]	train-mlogloss:0.21677	eval-mlogloss:0.18679

[I 2026-08-30 03:43:15,729] Trial 10 pruned. Trial was pruned at iteration 128.

[0]	train-mlogloss:1.08756	eval-mlogloss:1.08911
[1]	train-mlogloss:1.07649	eval-mlogloss:1.07819
[2]	train-mlogloss:1.07052	eval-mlogloss:1.07260
[3]	train-mlogloss:1.06543	eval-mlogloss:1.06711
[4]	train-mlogloss:1.05425	eval-mlogloss:1.05583
[5]	train-mlogloss:1.04186	eval-mlogloss:1.04312
[6]	train-mlogloss:1.03672	eval-mlogloss:1.03803
[7]	train-mlogloss:1.03062	eval-mlogloss:1.03153
[8]	train-mlogloss:1.01975	eval-mlogloss:1.02028
[9]	train-mlogloss:1.00808	eval-mlogloss:1.00824
[10]	train-mlogloss:0.99875	eval-mlogloss:0.99806
[11]	train-mlogloss:0.98918	eval-mlogloss:0.98762
[12]	train-mlogloss:0.97927	eval-mlogloss:0.97755
[13]	train-mlogloss:0.97195	eval-mlogloss:0.97000
[14]	train-mlogloss:0.96275	eval-mlogloss:0.96008
[15]	train-mlogloss:0.95356	eval-mlogloss:0.94998
[16]	train-mlogloss:0.94475	eval-mlogloss:0.94018
[17]	train-mlogloss:0.93314	eval-mlogloss:0.92780
[18]	train-mlogloss:0.92365	eval-mlogloss:0.91814
[19]	train-mlogloss:0.91433	eval-mlogloss:0.90827
[20]	train-mlogloss:0.90898	eval-mlogloss:0.90337
[21]	train-mlogloss:0.89975	eval-mlogloss:0.89388
[22]	train-mlogloss:0.89171	eval-mlogloss:0.88486
[23]	train-mlogloss:0.88783	eval-mlogloss:0.88144
[24]	train-mlogloss:0.87713	eval-mlogloss:0.86995
[25]	train-mlogloss:0.86646	eval-mlogloss:0.85868
[26]	train-mlogloss:0.85989	eval-mlogloss:0.85110
[27]	train-mlogloss:0.85573	eval-mlogloss:0.84682
[28]	train-mlogloss:0.84979	eval-mlogloss:0.84091
[29]	train-mlogloss:0.84164	eval-mlogloss:0.83227
[30]	train-mlogloss:0.83682	eval-mlogloss:0.82834
[31]	train-mlogloss:0.82961	eval-mlogloss:0.82042
[32]	train-mlogloss:0.82180	eval-mlogloss:0.81204
[33]	train-mlogloss:0.81849	eval-mlogloss:0.80899
[34]	train-mlogloss:0.80888	eval-mlogloss:0.79884
[35]	train-mlogloss:0.80177	eval-mlogloss:0.79178
[36]	train-mlogloss:0.79413	eval-mlogloss:0.78320
[37]	train-mlogloss:0.78981	eval-mlogloss:0.77931
[38]	train-mlogloss:0.78503	eval-mlogloss:0.77410
[39]	train-mlogloss:0.78087	eval-mlogloss:0.76969
[40]	train-mlogloss:0.77515	eval-mlogloss:0.76391
[41]	train-mlogloss:0.76963	eval-mlogloss:0.75842
[42]	train-mlogloss:0.76288	eval-mlogloss:0.75163
[43]	train-mlogloss:0.75773	eval-mlogloss:0.74628
[44]	train-mlogloss:0.75166	eval-mlogloss:0.74014
[45]	train-mlogloss:0.74331	eval-mlogloss:0.73090
[46]	train-mlogloss:0.73903	eval-mlogloss:0.72673
[47]	train-mlogloss:0.73237	eval-mlogloss:0.71966
[48]	train-mlogloss:0.72731	eval-mlogloss:0.71399
[49]	train-mlogloss:0.72376	eval-mlogloss:0.71030
[50]	train-mlogloss:0.71956	eval-mlogloss:0.70631
[51]	train-mlogloss:0.71382	eval-mlogloss:0.70063
[52]	train-mlogloss:0.70577	eval-mlogloss:0.69235
[53]	train-mlogloss:0.70028	eval-mlogloss:0.68632
[54]	train-mlogloss:0.69243	eval-mlogloss:0.67762
[55]	train-mlogloss:0.68653	eval-mlogloss:0.67109
[56]	train-mlogloss:0.68130	eval-mlogloss:0.66543
[57]	train-mlogloss:0.67859	eval-mlogloss:0.66252
[58]	train-mlogloss:0.67698	eval-mlogloss:0.66097
[59]	train-mlogloss:0.66963	eval-mlogloss:0.65301
[60]	train-mlogloss:0.66499	eval-mlogloss:0.64839
[61]	train-mlogloss:0.66144	eval-mlogloss:0.64484
[62]	train-mlogloss:0.65645	eval-mlogloss:0.63937
[63]	train-mlogloss:0.65320	eval-mlogloss:0.63645
[64]	train-mlogloss:0.65024	eval-mlogloss:0.63342
[65]	train-mlogloss:0.64856	eval-mlogloss:0.63243
[66]	train-mlogloss:0.64170	eval-mlogloss:0.62503
[67]	train-mlogloss:0.63800	eval-mlogloss:0.62143
[68]	train-mlogloss:0.63461	eval-mlogloss:0.61810
[69]	train-mlogloss:0.62873	eval-mlogloss:0.61168
[70]	train-mlogloss:0.62597	eval-mlogloss:0.60887
[71]	train-mlogloss:0.62042	eval-mlogloss:0.60265
[72]	train-mlogloss:0.61463	eval-mlogloss:0.59677
[73]	train-mlogloss:0.61275	eval-mlogloss:0.59500
[74]	train-mlogloss:0.60788	eval-mlogloss:0.58994
[75]	train-mlogloss:0.60574	eval-mlogloss:0.58786
[76]	train-mlogloss:0.60059	eval-mlogloss:0.58255
[77]	train-mlogloss:0.59846	eval-mlogloss:0.58046
[78]	train-mlogloss:0.59398	eval-mlogloss:0.57568
[79]	train-mlogloss:0.58851	eval-mlogloss:0.56970
[80]	train-mlogloss:0.58657	eval-mlogloss:0.56778
[81]	train-mlogloss:0.58251	eval-mlogloss:0.56367
[82]	train-mlogloss:0.58108	eval-mlogloss:0.56254
[83]	train-mlogloss:0.57517	eval-mlogloss:0.55611
[84]	train-mlogloss:0.57351	eval-mlogloss:0.55464
[85]	train-mlogloss:0.56743	eval-mlogloss:0.54806
[86]	train-mlogloss:0.56439	eval-mlogloss:0.54501
[87]	train-mlogloss:0.56003	eval-mlogloss:0.54045
[88]	train-mlogloss:0.55541	eval-mlogloss:0.53543
[89]	train-mlogloss:0.55254	eval-mlogloss:0.53208
[90]	train-mlogloss:0.54791	eval-mlogloss:0.52722
[91]	train-mlogloss:0.54551	eval-mlogloss:0.52509
[92]	train-mlogloss:0.54113	eval-mlogloss:0.52044
[93]	train-mlogloss:0.53734	eval-mlogloss:0.51632
[94]	train-mlogloss:0.53489	eval-mlogloss:0.51400
[95]	train-mlogloss:0.53018	eval-mlogloss:0.50885
[96]	train-mlogloss:0.52739	eval-mlogloss:0.50558
[97]	train-mlogloss:0.52206	eval-mlogloss:0.49993
[98]	train-mlogloss:0.52007	eval-mlogloss:0.49783
[99]	train-mlogloss:0.51608	eval-mlogloss:0.49357
[100]	train-mlogloss:0.51449	eval-mlogloss:0.49196
[101]	train-mlogloss:0.51285	eval-mlogloss:0.49050
[102]	train-mlogloss:0.50796	eval-mlogloss:0.48508
[103]	train-mlogloss:0.50447	eval-mlogloss:0.48156
[104]	train-mlogloss:0.50157	eval-mlogloss:0.47823
[105]	train-mlogloss:0.49655	eval-mlogloss:0.47283
[106]	train-mlogloss:0.49458	eval-mlogloss:0.47093
[107]	train-mlogloss:0.49201	eval-mlogloss:0.46857
[108]	train-mlogloss:0.48857	eval-mlogloss:0.46476
[109]	train-mlogloss:0.48479	eval-mlogloss:0.46079
[110]	train-mlogloss:0.48212	eval-mlogloss:0.45794
[111]	train-mlogloss:0.47953	eval-mlogloss:0.45531
[112]	train-mlogloss:0.47569	eval-mlogloss:0.45114
[113]	train-mlogloss:0.47486	eval-mlogloss:0.45043
[114]	train-mlogloss:0.47136	eval-mlogloss:0.44693
[115]	train-mlogloss:0.46689	eval-mlogloss:0.44235
[116]	train-mlogloss:0.46468	eval-mlogloss:0.43985
[117]	train-mlogloss:0.46117	eval-mlogloss:0.43625
[118]	train-mlogloss:0.45798	eval-mlogloss:0.43313
[119]	train-mlogloss:0.45415	eval-mlogloss:0.42904
[120]	train-mlogloss:0.44985	eval-mlogloss:0.42454
[121]	train-mlogloss:0.44660	eval-mlogloss:0.42109
[122]	train-mlogloss:0.44250	eval-mlogloss:0.41664
[123]	train-mlogloss:0.43985	eval-mlogloss:0.41382
[124]	train-mlogloss:0.43753	eval-mlogloss:0.41121
[125]	train-mlogloss:0.43390	eval-mlogloss:0.40740
[126]	train-mlogloss:0.43197	eval-mlogloss:0.40538
[127]	train-mlogloss:0.42891	eval-mlogloss:0.40210
[128]	train-mlogloss:0.42688	eval-mlogloss:0.40011
[129]	train-mlogloss:0.42512	eval-mlogloss:0.39805
[130]	train-mlogloss:0.42440	eval-mlogloss:0.39769
[131]	train-mlogloss:0.42310	eval-mlogloss:0.39627
[132]	train-mlogloss:0.42013	eval-mlogloss:0.39324
[133]	train-mlogloss:0.41790	eval-mlogloss:0.39093
[134]	train-mlogloss:0.41401	eval-mlogloss:0.38664
[135]	train-mlogloss:0.41305	eval-mlogloss:0.38578
[136]	train-mlogloss:0.41050	eval-mlogloss:0.38314
[137]	train-mlogloss:0.40789	eval-mlogloss:0.37984
[138]	train-mlogloss:0.40516	eval-mlogloss:0.37686
[139]	train-mlogloss:0.40163	eval-mlogloss:0.37292
[140]	train-mlogloss:0.39903	eval-mlogloss:0.36974
[141]	train-mlogloss:0.39658	eval-mlogloss:0.36716
[142]	train-mlogloss:0.39495	eval-mlogloss:0.36529
[143]	train-mlogloss:0.39230	eval-mlogloss:0.36289
[144]	train-mlogloss:0.39053	eval-mlogloss:0.36079
[145]	train-mlogloss:0.38731	eval-mlogloss:0.35721
[146]	train-mlogloss:0.38671	eval-mlogloss:0.35676
[147]	train-mlogloss:0.38408	eval-mlogloss:0.35391
[148]	train-mlogloss:0.38111	eval-mlogloss:0.35040
[149]	train-mlogloss:0.37986	eval-mlogloss:0.34916
[150]	train-mlogloss:0.37756	eval-mlogloss:0.34652
[151]	train-mlogloss:0.37683	eval-mlogloss:0.34595
[152]	train-mlogloss:0.37523	eval-mlogloss:0.34408
[153]	train-mlogloss:0.37304	eval-mlogloss:0.34157
[154]	train-mlogloss:0.37234	eval-mlogloss:0.34086
[155]	train-mlogloss:0.37019	eval-mlogloss:0.33826
[156]	train-mlogloss:0.36755	eval-mlogloss:0.33530
[157]	train-mlogloss:0.36454	eval-mlogloss:0.33178
[158]	train-mlogloss:0.36253	eval-mlogloss:0.32946
[159]	train-mlogloss:0.36001	eval-mlogloss:0.32669
[160]	train-mlogloss:0.35875	eval-mlogloss:0.32547
[161]	train-mlogloss:0.35707	eval-mlogloss:0.32356
[162]	train-mlogloss:0.35421	eval-mlogloss:0.32020
[163]	train-mlogloss:0.35278	eval-mlogloss:0.31855
[164]	train-mlogloss:0.35087	eval-mlogloss:0.31657
[165]	train-mlogloss:0.34948	eval-mlogloss:0.31497
[166]	train-mlogloss:0.34803	eval-mlogloss:0.31329
[167]	train-mlogloss:0.34662	eval-mlogloss:0.31148
[168]	train-mlogloss:0.34621	eval-mlogloss:0.31099
[169]	train-mlogloss:0.34413	eval-mlogloss:0.30871
[170]	train-mlogloss:0.34157	eval-mlogloss:0.30590
[171]	train-mlogloss:0.33946	eval-mlogloss:0.30364
[172]	train-mlogloss:0.33683	eval-mlogloss:0.30079
[173]	train-mlogloss:0.33500	eval-mlogloss:0.29864
[174]	train-mlogloss:0.33306	eval-mlogloss:0.29652
[175]	train-mlogloss:0.33197	eval-mlogloss:0.29559
[176]	train-mlogloss:0.33014	eval-mlogloss:0.29351
[177]	train-mlogloss:0.32839	eval-mlogloss:0.29141
[178]	train-mlogloss:0.32628	eval-mlogloss:0.28872
[179]	train-mlogloss:0.32463	eval-mlogloss:0.28671
[180]	train-mlogloss:0.32277	eval-mlogloss:0.28475
[181]	train-mlogloss:0.32106	eval-mlogloss:0.28282
[182]	train-mlogloss:0.31935	eval-mlogloss:0.28081
[183]	train-mlogloss:0.31790	eval-mlogloss:0.27925
[184]	train-mlogloss:0.31619	eval-mlogloss:0.27741
[185]	train-mlogloss:0.31468	eval-mlogloss:0.27588
[186]	train-mlogloss:0.31411	eval-mlogloss:0.27530
[187]	train-mlogloss:0.31273	eval-mlogloss:0.27388
[188]	train-mlogloss:0.31051	eval-mlogloss:0.27132
[189]	train-mlogloss:0.30975	eval-mlogloss:0.27057
[190]	train-mlogloss:0.30853	eval-mlogloss:0.26923
[191]	train-mlogloss:0.30691	eval-mlogloss:0.26742
[192]	train-mlogloss:0.30504	eval-mlogloss:0.26535
[193]	train-mlogloss:0.30419	eval-mlogloss:0.26456
[194]	train-mlogloss:0.30375	eval-mlogloss:0.26420
[195]	train-mlogloss:0.30277	eval-mlogloss:0.26315
[196]	train-mlogloss:0.30179	eval-mlogloss:0.26194
[197]	train-mlogloss:0.30053	eval-mlogloss:0.26072
[198]	train-mlogloss:0.29892	eval-mlogloss:0.25858
[199]	train-mlogloss:0.29738	eval-mlogloss:0.25689
[200]	train-mlogloss:0.29594	eval-mlogloss:0.25544
[201]	train-mlogloss:0.29547	eval-mlogloss:0.25485
[202]	train-mlogloss:0.29428	eval-mlogloss:0.25361
[203]	train-mlogloss:0.29334	eval-mlogloss:0.25257
[204]	train-mlogloss:0.29200	eval-mlogloss:0.25115
[205]	train-mlogloss:0.29094	eval-mlogloss:0.24981
[206]	train-mlogloss:0.29013	eval-mlogloss:0.24879
[207]	train-mlogloss:0.28870	eval-mlogloss:0.24725
[208]	train-mlogloss:0.28727	eval-mlogloss:0.24570
[209]	train-mlogloss:0.28692	eval-mlogloss:0.24557
[210]	train-mlogloss:0.28583	eval-mlogloss:0.24438
[211]	train-mlogloss:0.28498	eval-mlogloss:0.24344
[212]	train-mlogloss:0.28389	eval-mlogloss:0.24216
[213]	train-mlogloss:0.28233	eval-mlogloss:0.24033
[214]	train-mlogloss:0.28176	eval-mlogloss:0.23965
[215]	train-mlogloss:0.28011	eval-mlogloss:0.23769
[216]	train-mlogloss:0.27885	eval-mlogloss:0.23623
[217]	train-mlogloss:0.27784	eval-mlogloss:0.23502
[218]	train-mlogloss:0.27644	eval-mlogloss:0.23350
[219]	train-mlogloss:0.27470	eval-mlogloss:0.23137
[220]	train-mlogloss:0.27331	eval-mlogloss:0.22983
[221]	train-mlogloss:0.27230	eval-mlogloss:0.22859
[222]	train-mlogloss:0.27114	eval-mlogloss:0.22727
[223]	train-mlogloss:0.27065	eval-mlogloss:0.22667
[224]	train-mlogloss:0.26975	eval-mlogloss:0.22571
[225]	train-mlogloss:0.26898	eval-mlogloss:0.22478
[226]	train-mlogloss:0.26855	eval-mlogloss:0.22444
[227]	train-mlogloss:0.26698	eval-mlogloss:0.22263
[228]	train-mlogloss:0.26598	eval-mlogloss:0.22157
[229]	train-mlogloss:0.26549	eval-mlogloss:0.22101
[230]	train-mlogloss:0.26431	eval-mlogloss:0.21962
[231]	train-mlogloss:0.26358	eval-mlogloss:0.21885
[232]	train-mlogloss:0.26199	eval-mlogloss:0.21707
[233]	train-mlogloss:0.26160	eval-mlogloss:0.21655
[234]	train-mlogloss:0.26088	eval-mlogloss:0.21583
[235]	train-mlogloss:0.25944	eval-mlogloss:0.21433
[236]	train-mlogloss:0.25833	eval-mlogloss:0.21310
[237]	train-mlogloss:0.25763	eval-mlogloss:0.21232
[238]	train-mlogloss:0.25697	eval-mlogloss:0.21165
[239]	train-mlogloss:0.25593	eval-mlogloss:0.21042
[240]	train-mlogloss:0.25504	eval-mlogloss:0.20923
[241]	train-mlogloss:0.25469	eval-mlogloss:0.20898
[242]	train-mlogloss:0.25401	eval-mlogloss:0.20824
[243]	train-mlogloss:0.25366	eval-mlogloss:0.20790
[244]	train-mlogloss:0.25332	eval-mlogloss:0.20755
[245]	train-mlogloss:0.25223	eval-mlogloss:0.20627
[246]	train-mlogloss:0.25142	eval-mlogloss:0.20540
[247]	train-mlogloss:0.25075	eval-mlogloss:0.20467
[248]	train-mlogloss:0.24992	eval-mlogloss:0.20394
[249]	train-mlogloss:0.24893	eval-mlogloss:0.20282
[250]	train-mlogloss:0.24865	eval-mlogloss:0.20242
[251]	train-mlogloss:0.24746	eval-mlogloss:0.20105
[252]	train-mlogloss:0.24602	eval-mlogloss:0.19928
[253]	train-mlogloss:0.24473	eval-mlogloss:0.19772
[254]	train-mlogloss:0.24460	eval-mlogloss:0.19751
[255]	train-mlogloss:0.24373	eval-mlogloss:0.19641
[256]	train-mlogloss:0.24249	eval-mlogloss:0.19500
[257]	train-mlogloss:0.24227	eval-mlogloss:0.19477
[258]	train-mlogloss:0.24215	eval-mlogloss:0.19473
[259]	train-mlogloss:0.24100	eval-mlogloss:0.19333
[260]	train-mlogloss:0.24087	eval-mlogloss:0.19333
[261]	train-mlogloss:0.24024	eval-mlogloss:0.19268
[262]	train-mlogloss:0.23999	eval-mlogloss:0.19241
[263]	train-mlogloss:0.23912	eval-mlogloss:0.19130
[264]	train-mlogloss:0.23791	eval-mlogloss:0.19000
[265]	train-mlogloss:0.23723	eval-mlogloss:0.18920
[266]	train-mlogloss:0.23695	eval-mlogloss:0.18890
[267]	train-mlogloss:0.23648	eval-mlogloss:0.18835
[268]	train-mlogloss:0.23574	eval-mlogloss:0.18750
[269]	train-mlogloss:0.23545	eval-mlogloss:0.18726
[270]	train-mlogloss:0.23534	eval-mlogloss:0.18708
[271]	train-mlogloss:0.23444	eval-mlogloss:0.18596
[272]	train-mlogloss:0.23384	eval-mlogloss:0.18529
[273]	train-mlogloss:0.23350	eval-mlogloss:0.18488
[274]	train-mlogloss:0.23303	eval-mlogloss:0.18447
[275]	train-mlogloss:0.23243	eval-mlogloss:0.18397
[276]	train-mlogloss:0.23195	eval-mlogloss:0.18335
[277]	train-mlogloss:0.23085	eval-mlogloss:0.18216
[278]	train-mlogloss:0.23078	eval-mlogloss:0.18217
[279]	train-mlogloss:0.23033	eval-mlogloss:0.18156
[280]	train-mlogloss:0.22983	eval-mlogloss:0.18097
[281]	train-mlogloss:0.22867	eval-mlogloss:0.17972
[282]	train-mlogloss:0.22829	eval-mlogloss:0.17920
[283]	train-mlogloss:0.22781	eval-mlogloss:0.17865
[284]	train-mlogloss:0.22715	eval-mlogloss:0.17781
[285]	train-mlogloss:0.22676	eval-mlogloss:0.17741
[286]	train-mlogloss:0.22665	eval-mlogloss:0.17727
[287]	train-mlogloss:0.22609	eval-mlogloss:0.17663
[288]	train-mlogloss:0.22596	eval-mlogloss:0.17648
[289]	train-mlogloss:0.22591	eval-mlogloss:0.17662
[290]	train-mlogloss:0.22528	eval-mlogloss:0.17582
[291]	train-mlogloss:0.22519	eval-mlogloss:0.17569
[292]	train-mlogloss:0.22459	eval-mlogloss:0.17502
[293]	train-mlogloss:0.22404	eval-mlogloss:0.17428
[294]	train-mlogloss:0.22390	eval-mlogloss:0.17424
[295]	train-mlogloss:0.22347	eval-mlogloss:0.17368
[296]	train-mlogloss:0.22282	eval-mlogloss:0.17295
[297]	train-mlogloss:0.22223	eval-mlogloss:0.17210
[298]	train-mlogloss:0.22203	eval-mlogloss:0.17189
[299]	train-mlogloss:0.22148	eval-mlogloss:0.17129

[I 2026-08-30 03:43:16,300] Trial 11 finished with value: 1.0 and parameters: {'lambda': 1.4086669585210275e-06, 'alpha': 2.6991793743142118e-08, 'eta': 0.011173778620260852, 'gamma': 7.958892738139554e-06, 'max_depth': 9, 'min_child_weight': 6, 'subsample': 0.6714626745007884, 'colsample_bytree': 0.49533437047857093}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.97077	eval-mlogloss:0.95909
[1]	train-mlogloss:0.83224	eval-mlogloss:0.81666

[I 2026-08-30 03:43:16,314] Trial 12 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.81886	eval-mlogloss:0.79983
[1]	train-mlogloss:0.63802	eval-mlogloss:0.60457

[I 2026-08-30 03:43:16,327] Trial 13 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.05350	eval-mlogloss:1.05112
[1]	train-mlogloss:1.01261	eval-mlogloss:1.00873
[2]	train-mlogloss:0.96962	eval-mlogloss:0.96037
[3]	train-mlogloss:0.94248	eval-mlogloss:0.93369
[4]	train-mlogloss:0.90649	eval-mlogloss:0.89629
[5]	train-mlogloss:0.88156	eval-mlogloss:0.86845
[6]	train-mlogloss:0.85562	eval-mlogloss:0.84156
[7]	train-mlogloss:0.83142	eval-mlogloss:0.81409

[I 2026-08-30 03:43:16,344] Trial 14 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.84751	eval-mlogloss:0.84332
[1]	train-mlogloss:0.61530	eval-mlogloss:0.59936

[I 2026-08-30 03:43:16,358] Trial 15 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.98064	eval-mlogloss:0.98195
[1]	train-mlogloss:0.87561	eval-mlogloss:0.87752
[2]	train-mlogloss:0.82607	eval-mlogloss:0.85002
[3]	train-mlogloss:0.78222	eval-mlogloss:0.81820
[4]	train-mlogloss:0.70677	eval-mlogloss:0.74148
[5]	train-mlogloss:0.63028	eval-mlogloss:0.65693
[6]	train-mlogloss:0.60329	eval-mlogloss:0.63244
[7]	train-mlogloss:0.57054	eval-mlogloss:0.60184

[I 2026-08-30 03:43:16,407] Trial 16 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.95540	eval-mlogloss:0.94925
[1]	train-mlogloss:0.80664	eval-mlogloss:0.79248

[I 2026-08-30 03:43:16,421] Trial 17 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.87655	eval-mlogloss:0.87639
[1]	train-mlogloss:0.70479	eval-mlogloss:0.69542

[I 2026-08-30 03:43:16,434] Trial 18 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.05016	eval-mlogloss:1.04934
[1]	train-mlogloss:0.98954	eval-mlogloss:0.98513
[2]	train-mlogloss:0.93504	eval-mlogloss:0.92692
[3]	train-mlogloss:0.89001	eval-mlogloss:0.88076
[4]	train-mlogloss:0.84243	eval-mlogloss:0.83082
[5]	train-mlogloss:0.80283	eval-mlogloss:0.78867
[6]	train-mlogloss:0.76827	eval-mlogloss:0.75134
[7]	train-mlogloss:0.74141	eval-mlogloss:0.72455

[I 2026-08-30 03:43:16,453] Trial 19 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.87982	eval-mlogloss:0.86267
[1]	train-mlogloss:0.72105	eval-mlogloss:0.68997

[I 2026-08-30 03:43:16,506] Trial 20 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03609	eval-mlogloss:1.03228
[1]	train-mlogloss:0.98599	eval-mlogloss:0.98068
[2]	train-mlogloss:0.94568	eval-mlogloss:0.93884
[3]	train-mlogloss:0.91976	eval-mlogloss:0.91289
[4]	train-mlogloss:0.87849	eval-mlogloss:0.87450
[5]	train-mlogloss:0.85037	eval-mlogloss:0.84613
[6]	train-mlogloss:0.82152	eval-mlogloss:0.81446
[7]	train-mlogloss:0.78800	eval-mlogloss:0.77422

[I 2026-08-30 03:43:16,524] Trial 21 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.04767	eval-mlogloss:1.04355
[1]	train-mlogloss:0.98442	eval-mlogloss:0.97833

[I 2026-08-30 03:43:16,538] Trial 22 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.01025	eval-mlogloss:1.00150
[1]	train-mlogloss:0.91003	eval-mlogloss:0.89472

[I 2026-08-30 03:43:16,551] Trial 23 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.07017	eval-mlogloss:1.07061
[1]	train-mlogloss:1.03500	eval-mlogloss:1.03348
[2]	train-mlogloss:1.00141	eval-mlogloss:0.99740
[3]	train-mlogloss:0.97429	eval-mlogloss:0.96848
[4]	train-mlogloss:0.94328	eval-mlogloss:0.93606
[5]	train-mlogloss:0.91709	eval-mlogloss:0.90919
[6]	train-mlogloss:0.89266	eval-mlogloss:0.88307
[7]	train-mlogloss:0.87521	eval-mlogloss:0.86637

[I 2026-08-30 03:43:16,600] Trial 24 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.02813	eval-mlogloss:1.02599
[1]	train-mlogloss:0.94619	eval-mlogloss:0.93978

[I 2026-08-30 03:43:16,614] Trial 25 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.95963	eval-mlogloss:0.95514
[1]	train-mlogloss:0.81715	eval-mlogloss:0.80875

[I 2026-08-30 03:43:16,628] Trial 26 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08781	eval-mlogloss:1.08980
[1]	train-mlogloss:1.08053	eval-mlogloss:1.08224
[2]	train-mlogloss:1.07537	eval-mlogloss:1.07690
[3]	train-mlogloss:1.07206	eval-mlogloss:1.07269
[4]	train-mlogloss:1.06529	eval-mlogloss:1.06738
[5]	train-mlogloss:1.05742	eval-mlogloss:1.05955
[6]	train-mlogloss:1.05239	eval-mlogloss:1.05505
[7]	train-mlogloss:1.04556	eval-mlogloss:1.04781
[8]	train-mlogloss:1.03693	eval-mlogloss:1.04003
[9]	train-mlogloss:1.02808	eval-mlogloss:1.03123
[10]	train-mlogloss:1.02199	eval-mlogloss:1.02397
[11]	train-mlogloss:1.01119	eval-mlogloss:1.01178
[12]	train-mlogloss:0.99943	eval-mlogloss:0.99862
[13]	train-mlogloss:0.99120	eval-mlogloss:0.98994
[14]	train-mlogloss:0.98100	eval-mlogloss:0.97844
[15]	train-mlogloss:0.97098	eval-mlogloss:0.96807
[16]	train-mlogloss:0.96086	eval-mlogloss:0.95690
[17]	train-mlogloss:0.95369	eval-mlogloss:0.94941
[18]	train-mlogloss:0.94747	eval-mlogloss:0.94391
[19]	train-mlogloss:0.94025	eval-mlogloss:0.93594
[20]	train-mlogloss:0.93405	eval-mlogloss:0.93003
[21]	train-mlogloss:0.92689	eval-mlogloss:0.92290
[22]	train-mlogloss:0.91863	eval-mlogloss:0.91389
[23]	train-mlogloss:0.91556	eval-mlogloss:0.91103
[24]	train-mlogloss:0.90742	eval-mlogloss:0.90203
[25]	train-mlogloss:0.89926	eval-mlogloss:0.89408
[26]	train-mlogloss:0.89364	eval-mlogloss:0.88813
[27]	train-mlogloss:0.88946	eval-mlogloss:0.88337
[28]	train-mlogloss:0.88594	eval-mlogloss:0.87954
[29]	train-mlogloss:0.88035	eval-mlogloss:0.87298
[30]	train-mlogloss:0.87641	eval-mlogloss:0.86827
[31]	train-mlogloss:0.86817	eval-mlogloss:0.85984
[32]	train-mlogloss:0.86223	eval-mlogloss:0.85333
[33]	train-mlogloss:0.85889	eval-mlogloss:0.84952
[34]	train-mlogloss:0.85197	eval-mlogloss:0.84215
[35]	train-mlogloss:0.84347	eval-mlogloss:0.83289
[36]	train-mlogloss:0.83950	eval-mlogloss:0.82914
[37]	train-mlogloss:0.83486	eval-mlogloss:0.82301
[38]	train-mlogloss:0.83072	eval-mlogloss:0.81910
[39]	train-mlogloss:0.82725	eval-mlogloss:0.81522
[40]	train-mlogloss:0.82085	eval-mlogloss:0.80839
[41]	train-mlogloss:0.81772	eval-mlogloss:0.80530
[42]	train-mlogloss:0.81085	eval-mlogloss:0.79887
[43]	train-mlogloss:0.80841	eval-mlogloss:0.79666
[44]	train-mlogloss:0.80401	eval-mlogloss:0.79227
[45]	train-mlogloss:0.79765	eval-mlogloss:0.78569
[46]	train-mlogloss:0.79590	eval-mlogloss:0.78399
[47]	train-mlogloss:0.79241	eval-mlogloss:0.77984
[48]	train-mlogloss:0.79147	eval-mlogloss:0.77929
[49]	train-mlogloss:0.78838	eval-mlogloss:0.77587
[50]	train-mlogloss:0.78347	eval-mlogloss:0.77126
[51]	train-mlogloss:0.77950	eval-mlogloss:0.76733
[52]	train-mlogloss:0.77008	eval-mlogloss:0.75738
[53]	train-mlogloss:0.76356	eval-mlogloss:0.75020
[54]	train-mlogloss:0.75595	eval-mlogloss:0.74225
[55]	train-mlogloss:0.74963	eval-mlogloss:0.73538
[56]	train-mlogloss:0.74441	eval-mlogloss:0.73048
[57]	train-mlogloss:0.74266	eval-mlogloss:0.72851
[58]	train-mlogloss:0.74146	eval-mlogloss:0.72769
[59]	train-mlogloss:0.73601	eval-mlogloss:0.72238
[60]	train-mlogloss:0.73112	eval-mlogloss:0.71738
[61]	train-mlogloss:0.73010	eval-mlogloss:0.71655
[62]	train-mlogloss:0.72539	eval-mlogloss:0.71127
[63]	train-mlogloss:0.72243	eval-mlogloss:0.70807
[64]	train-mlogloss:0.72055	eval-mlogloss:0.70549
[65]	train-mlogloss:0.71897	eval-mlogloss:0.70396
[66]	train-mlogloss:0.71378	eval-mlogloss:0.69853
[67]	train-mlogloss:0.70941	eval-mlogloss:0.69421
[68]	train-mlogloss:0.70771	eval-mlogloss:0.69303
[69]	train-mlogloss:0.70593	eval-mlogloss:0.69112
[70]	train-mlogloss:0.70315	eval-mlogloss:0.68816
[71]	train-mlogloss:0.70025	eval-mlogloss:0.68500
[72]	train-mlogloss:0.69465	eval-mlogloss:0.67935
[73]	train-mlogloss:0.69303	eval-mlogloss:0.67766
[74]	train-mlogloss:0.68763	eval-mlogloss:0.67179
[75]	train-mlogloss:0.68588	eval-mlogloss:0.66974
[76]	train-mlogloss:0.68268	eval-mlogloss:0.66584
[77]	train-mlogloss:0.68030	eval-mlogloss:0.66295
[78]	train-mlogloss:0.67988	eval-mlogloss:0.66245
[79]	train-mlogloss:0.67541	eval-mlogloss:0.65772
[80]	train-mlogloss:0.67426	eval-mlogloss:0.65581
[81]	train-mlogloss:0.67423	eval-mlogloss:0.65576
[82]	train-mlogloss:0.67242	eval-mlogloss:0.65388
[83]	train-mlogloss:0.66882	eval-mlogloss:0.65011
[84]	train-mlogloss:0.66882	eval-mlogloss:0.65010
[85]	train-mlogloss:0.66649	eval-mlogloss:0.64760
[86]	train-mlogloss:0.66366	eval-mlogloss:0.64404
[87]	train-mlogloss:0.66279	eval-mlogloss:0.64345
[88]	train-mlogloss:0.65939	eval-mlogloss:0.63974
[89]	train-mlogloss:0.65650	eval-mlogloss:0.63638
[90]	train-mlogloss:0.65341	eval-mlogloss:0.63327
[91]	train-mlogloss:0.65086	eval-mlogloss:0.63076
[92]	train-mlogloss:0.64711	eval-mlogloss:0.62657
[93]	train-mlogloss:0.64209	eval-mlogloss:0.62127
[94]	train-mlogloss:0.64206	eval-mlogloss:0.62135
[95]	train-mlogloss:0.63925	eval-mlogloss:0.61784
[96]	train-mlogloss:0.63674	eval-mlogloss:0.61496
[97]	train-mlogloss:0.63153	eval-mlogloss:0.61023
[98]	train-mlogloss:0.62926	eval-mlogloss:0.60743
[99]	train-mlogloss:0.62821	eval-mlogloss:0.60677
[100]	train-mlogloss:0.62671	eval-mlogloss:0.60522
[101]	train-mlogloss:0.62498	eval-mlogloss:0.60380
[102]	train-mlogloss:0.62498	eval-mlogloss:0.60384
[103]	train-mlogloss:0.62244	eval-mlogloss:0.60111
[104]	train-mlogloss:0.62102	eval-mlogloss:0.59955
[105]	train-mlogloss:0.61585	eval-mlogloss:0.59407
[106]	train-mlogloss:0.61411	eval-mlogloss:0.59211
[107]	train-mlogloss:0.61181	eval-mlogloss:0.58941
[108]	train-mlogloss:0.61172	eval-mlogloss:0.58943
[109]	train-mlogloss:0.61091	eval-mlogloss:0.58852
[110]	train-mlogloss:0.61053	eval-mlogloss:0.58793
[111]	train-mlogloss:0.61037	eval-mlogloss:0.58791
[112]	train-mlogloss:0.60795	eval-mlogloss:0.58546
[113]	train-mlogloss:0.60726	eval-mlogloss:0.58481
[114]	train-mlogloss:0.60364	eval-mlogloss:0.58107
[115]	train-mlogloss:0.59934	eval-mlogloss:0.57712
[116]	train-mlogloss:0.59649	eval-mlogloss:0.57400
[117]	train-mlogloss:0.59390	eval-mlogloss:0.57118
[118]	train-mlogloss:0.59139	eval-mlogloss:0.56838
[119]	train-mlogloss:0.58896	eval-mlogloss:0.56562
[120]	train-mlogloss:0.58865	eval-mlogloss:0.56538
[121]	train-mlogloss:0.58863	eval-mlogloss:0.56555
[122]	train-mlogloss:0.58437	eval-mlogloss:0.56099
[123]	train-mlogloss:0.58426	eval-mlogloss:0.56082
[124]	train-mlogloss:0.58302	eval-mlogloss:0.55958
[125]	train-mlogloss:0.58295	eval-mlogloss:0.55946
[126]	train-mlogloss:0.58292	eval-mlogloss:0.55943
[127]	train-mlogloss:0.58099	eval-mlogloss:0.55736
[128]	train-mlogloss:0.57993	eval-mlogloss:0.55609
[129]	train-mlogloss:0.57993	eval-mlogloss:0.55610
[130]	train-mlogloss:0.57885	eval-mlogloss:0.55546
[131]	train-mlogloss:0.57839	eval-mlogloss:0.55468
[132]	train-mlogloss:0.57759	eval-mlogloss:0.55379
[133]	train-mlogloss:0.57729	eval-mlogloss:0.55354
[134]	train-mlogloss:0.57487	eval-mlogloss:0.55062
[135]	train-mlogloss:0.57371	eval-mlogloss:0.54941
[136]	train-mlogloss:0.57350	eval-mlogloss:0.54930
[137]	train-mlogloss:0.57086	eval-mlogloss:0.54641
[138]	train-mlogloss:0.56859	eval-mlogloss:0.54382
[139]	train-mlogloss:0.56742	eval-mlogloss:0.54300
[140]	train-mlogloss:0.56489	eval-mlogloss:0.54022
[141]	train-mlogloss:0.56271	eval-mlogloss:0.53716
[142]	train-mlogloss:0.56270	eval-mlogloss:0.53720
[143]	train-mlogloss:0.56068	eval-mlogloss:0.53496
[144]	train-mlogloss:0.55936	eval-mlogloss:0.53367
[145]	train-mlogloss:0.55918	eval-mlogloss:0.53361
[146]	train-mlogloss:0.55907	eval-mlogloss:0.53365
[147]	train-mlogloss:0.55640	eval-mlogloss:0.53068
[148]	train-mlogloss:0.55447	eval-mlogloss:0.52827
[149]	train-mlogloss:0.55416	eval-mlogloss:0.52762
[150]	train-mlogloss:0.55211	eval-mlogloss:0.52507
[151]	train-mlogloss:0.55109	eval-mlogloss:0.52408
[152]	train-mlogloss:0.54924	eval-mlogloss:0.52194
[153]	train-mlogloss:0.54684	eval-mlogloss:0.51938
[154]	train-mlogloss:0.54652	eval-mlogloss:0.51910
[155]	train-mlogloss:0.54579	eval-mlogloss:0.51805
[156]	train-mlogloss:0.54372	eval-mlogloss:0.51554
[157]	train-mlogloss:0.54365	eval-mlogloss:0.51551
[158]	train-mlogloss:0.54344	eval-mlogloss:0.51548
[159]	train-mlogloss:0.54331	eval-mlogloss:0.51556
[160]	train-mlogloss:0.54321	eval-mlogloss:0.51546
[161]	train-mlogloss:0.54316	eval-mlogloss:0.51535
[162]	train-mlogloss:0.54309	eval-mlogloss:0.51540
[163]	train-mlogloss:0.54281	eval-mlogloss:0.51521
[164]	train-mlogloss:0.54078	eval-mlogloss:0.51321
[165]	train-mlogloss:0.54078	eval-mlogloss:0.51320
[166]	train-mlogloss:0.54034	eval-mlogloss:0.51261
[167]	train-mlogloss:0.53970	eval-mlogloss:0.51182
[168]	train-mlogloss:0.53977	eval-mlogloss:0.51196
[169]	train-mlogloss:0.53948	eval-mlogloss:0.51129
[170]	train-mlogloss:0.53567	eval-mlogloss:0.50692
[171]	train-mlogloss:0.53509	eval-mlogloss:0.50598
[172]	train-mlogloss:0.53282	eval-mlogloss:0.50360
[173]	train-mlogloss:0.53226	eval-mlogloss:0.50284
[174]	train-mlogloss:0.53224	eval-mlogloss:0.50289
[175]	train-mlogloss:0.53191	eval-mlogloss:0.50220
[176]	train-mlogloss:0.53173	eval-mlogloss:0.50197
[177]	train-mlogloss:0.53160	eval-mlogloss:0.50183
[178]	train-mlogloss:0.53009	eval-mlogloss:0.50020
[179]	train-mlogloss:0.52982	eval-mlogloss:0.49976
[180]	train-mlogloss:0.52982	eval-mlogloss:0.49976
[181]	train-mlogloss:0.52956	eval-mlogloss:0.49909
[182]	train-mlogloss:0.52765	eval-mlogloss:0.49710
[183]	train-mlogloss:0.52652	eval-mlogloss:0.49619
[184]	train-mlogloss:0.52647	eval-mlogloss:0.49622
[185]	train-mlogloss:0.52628	eval-mlogloss:0.49601
[186]	train-mlogloss:0.52628	eval-mlogloss:0.49605
[187]	train-mlogloss:0.52628	eval-mlogloss:0.49602
[188]	train-mlogloss:0.52600	eval-mlogloss:0.49575
[189]	train-mlogloss:0.52592	eval-mlogloss:0.49558
[190]	train-mlogloss:0.52571	eval-mlogloss:0.49518
[191]	train-mlogloss:0.52571	eval-mlogloss:0.49517
[192]	train-mlogloss:0.52395	eval-mlogloss:0.49318
[193]	train-mlogloss:0.52360	eval-mlogloss:0.49297
[194]	train-mlogloss:0.52350	eval-mlogloss:0.49287
[195]	train-mlogloss:0.52292	eval-mlogloss:0.49227
[196]	train-mlogloss:0.52131	eval-mlogloss:0.49016
[197]	train-mlogloss:0.52131	eval-mlogloss:0.49024
[198]	train-mlogloss:0.51948	eval-mlogloss:0.48808
[199]	train-mlogloss:0.51948	eval-mlogloss:0.48810
[200]	train-mlogloss:0.51921	eval-mlogloss:0.48784
[201]	train-mlogloss:0.51892	eval-mlogloss:0.48716
[202]	train-mlogloss:0.51895	eval-mlogloss:0.48720
[203]	train-mlogloss:0.51878	eval-mlogloss:0.48678
[204]	train-mlogloss:0.51865	eval-mlogloss:0.48664
[205]	train-mlogloss:0.51825	eval-mlogloss:0.48611
[206]	train-mlogloss:0.51821	eval-mlogloss:0.48601
[207]	train-mlogloss:0.51773	eval-mlogloss:0.48519
[208]	train-mlogloss:0.51740	eval-mlogloss:0.48453
[209]	train-mlogloss:0.51740	eval-mlogloss:0.48452
[210]	train-mlogloss:0.51733	eval-mlogloss:0.48449
[211]	train-mlogloss:0.51686	eval-mlogloss:0.48380
[212]	train-mlogloss:0.51676	eval-mlogloss:0.48373
[213]	train-mlogloss:0.51477	eval-mlogloss:0.48156
[214]	train-mlogloss:0.51473	eval-mlogloss:0.48154
[215]	train-mlogloss:0.51468	eval-mlogloss:0.48147
[216]	train-mlogloss:0.51467	eval-mlogloss:0.48151
[217]	train-mlogloss:0.51299	eval-mlogloss:0.47940
[218]	train-mlogloss:0.50986	eval-mlogloss:0.47587
[219]	train-mlogloss:0.50859	eval-mlogloss:0.47453
[220]	train-mlogloss:0.50859	eval-mlogloss:0.47451
[221]	train-mlogloss:0.50686	eval-mlogloss:0.47218
[222]	train-mlogloss:0.50684	eval-mlogloss:0.47222
[223]	train-mlogloss:0.50630	eval-mlogloss:0.47143
[224]	train-mlogloss:0.50601	eval-mlogloss:0.47126
[225]	train-mlogloss:0.50601	eval-mlogloss:0.47123
[226]	train-mlogloss:0.50580	eval-mlogloss:0.47103
[227]	train-mlogloss:0.50558	eval-mlogloss:0.47089
[228]	train-mlogloss:0.50384	eval-mlogloss:0.46899
[229]	train-mlogloss:0.50349	eval-mlogloss:0.46835
[230]	train-mlogloss:0.50171	eval-mlogloss:0.46611
[231]	train-mlogloss:0.50152	eval-mlogloss:0.46570
[232]	train-mlogloss:0.50141	eval-mlogloss:0.46566
[233]	train-mlogloss:0.50120	eval-mlogloss:0.46538
[234]	train-mlogloss:0.50120	eval-mlogloss:0.46542
[235]	train-mlogloss:0.50100	eval-mlogloss:0.46524
[236]	train-mlogloss:0.50102	eval-mlogloss:0.46520
[237]	train-mlogloss:0.50101	eval-mlogloss:0.46520
[238]	train-mlogloss:0.50091	eval-mlogloss:0.46505
[239]	train-mlogloss:0.50079	eval-mlogloss:0.46518
[240]	train-mlogloss:0.50083	eval-mlogloss:0.46520
[241]	train-mlogloss:0.50078	eval-mlogloss:0.46513
[242]	train-mlogloss:0.49900	eval-mlogloss:0.46306
[243]	train-mlogloss:0.49888	eval-mlogloss:0.46299
[244]	train-mlogloss:0.49883	eval-mlogloss:0.46313
[245]	train-mlogloss:0.49880	eval-mlogloss:0.46322
[246]	train-mlogloss:0.49880	eval-mlogloss:0.46328
[247]	train-mlogloss:0.49876	eval-mlogloss:0.46326
[248]	train-mlogloss:0.49870	eval-mlogloss:0.46318
[249]	train-mlogloss:0.49870	eval-mlogloss:0.46317
[250]	train-mlogloss:0.49873	eval-mlogloss:0.46313
[251]	train-mlogloss:0.49862	eval-mlogloss:0.46310
[252]	train-mlogloss:0.49853	eval-mlogloss:0.46297
[253]	train-mlogloss:0.49639	eval-mlogloss:0.46026
[254]	train-mlogloss:0.49620	eval-mlogloss:0.45975
[255]	train-mlogloss:0.49621	eval-mlogloss:0.45972
[256]	train-mlogloss:0.49590	eval-mlogloss:0.45955
[257]	train-mlogloss:0.49590	eval-mlogloss:0.45956
[258]	train-mlogloss:0.49579	eval-mlogloss:0.45948
[259]	train-mlogloss:0.49578	eval-mlogloss:0.45949
[260]	train-mlogloss:0.49576	eval-mlogloss:0.45958
[261]	train-mlogloss:0.49565	eval-mlogloss:0.45948
[262]	train-mlogloss:0.49537	eval-mlogloss:0.45886
[263]	train-mlogloss:0.49502	eval-mlogloss:0.45864
[264]	train-mlogloss:0.49348	eval-mlogloss:0.45691
[265]	train-mlogloss:0.49331	eval-mlogloss:0.45680
[266]	train-mlogloss:0.49331	eval-mlogloss:0.45681
[267]	train-mlogloss:0.49308	eval-mlogloss:0.45636
[268]	train-mlogloss:0.49308	eval-mlogloss:0.45636
[269]	train-mlogloss:0.49299	eval-mlogloss:0.45633
[270]	train-mlogloss:0.49264	eval-mlogloss:0.45573
[271]	train-mlogloss:0.49252	eval-mlogloss:0.45567
[272]	train-mlogloss:0.49253	eval-mlogloss:0.45564
[273]	train-mlogloss:0.49238	eval-mlogloss:0.45549
[274]	train-mlogloss:0.49233	eval-mlogloss:0.45541
[275]	train-mlogloss:0.49051	eval-mlogloss:0.45369
[276]	train-mlogloss:0.49053	eval-mlogloss:0.45361
[277]	train-mlogloss:0.49052	eval-mlogloss:0.45359
[278]	train-mlogloss:0.49054	eval-mlogloss:0.45352
[279]	train-mlogloss:0.49052	eval-mlogloss:0.45357
[280]	train-mlogloss:0.49050	eval-mlogloss:0.45362
[281]	train-mlogloss:0.49027	eval-mlogloss:0.45352
[282]	train-mlogloss:0.49020	eval-mlogloss:0.45344
[283]	train-mlogloss:0.48986	eval-mlogloss:0.45303
[284]	train-mlogloss:0.48916	eval-mlogloss:0.45232
[285]	train-mlogloss:0.48918	eval-mlogloss:0.45236
[286]	train-mlogloss:0.48918	eval-mlogloss:0.45237
[287]	train-mlogloss:0.48916	eval-mlogloss:0.45242
[288]	train-mlogloss:0.48903	eval-mlogloss:0.45232
[289]	train-mlogloss:0.48892	eval-mlogloss:0.45209
[290]	train-mlogloss:0.48887	eval-mlogloss:0.45206
[291]	train-mlogloss:0.48845	eval-mlogloss:0.45142
[292]	train-mlogloss:0.48700	eval-mlogloss:0.44935
[293]	train-mlogloss:0.48700	eval-mlogloss:0.44933
[294]	train-mlogloss:0.48697	eval-mlogloss:0.44931
[295]	train-mlogloss:0.48695	eval-mlogloss:0.44932
[296]	train-mlogloss:0.48682	eval-mlogloss:0.44927
[297]	train-mlogloss:0.48676	eval-mlogloss:0.44939
[298]	train-mlogloss:0.48673	eval-mlogloss:0.44939
[299]	train-mlogloss:0.48675	eval-mlogloss:0.44941

[I 2026-08-30 03:43:17,094] Trial 27 finished with value: 0.9666666666666667 and parameters: {'lambda': 1.5345505859562681e-06, 'alpha': 4.1367964698955037e-08, 'eta': 0.013866737028509574, 'gamma': 0.00032187899717406006, 'max_depth': 6, 'min_child_weight': 10, 'subsample': 0.4785969372973241, 'colsample_bytree': 0.45254687891336204}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.95193	eval-mlogloss:0.94241
[1]	train-mlogloss:0.83356	eval-mlogloss:0.81455

[I 2026-08-30 03:43:17,108] Trial 28 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.90474	eval-mlogloss:0.88777
[1]	train-mlogloss:0.71459	eval-mlogloss:0.68570

[I 2026-08-30 03:43:17,122] Trial 29 pruned. Trial was pruned at iteration 2.

Best trial: {'lambda': 3.2246298560619254e-07, 'alpha': 1.316660938476552e-07, 'eta': 0.03196587611314471, 'gamma': 0.0004958214429954585, 'max_depth': 9, 'min_child_weight': 4, 'subsample': 0.5130535342673512, 'colsample_bytree': 0.5601174334707635}
Best accuracy: 1.0

In [40]:
! pip install optuna-integration[xgboost]

Requirement already satisfied: optuna-integration[xgboost] in /usr/local/lib/python3.13/dist-packages (4.9.0)
Requirement already satisfied: optuna in /usr/local/lib/python3.13/dist-packages (from optuna-integration[xgboost]) (4.9.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.13/dist-packages (from optuna-integration[xgboost]) (3.4.1)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (1.19.1)
Requirement already satisfied: colorlog in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (6.12.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (26.3)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.52)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.13/dist-packages (from optuna->optuna-integration[xgboost]) (6.0.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from xgboost->optuna-integration[xgboost]) (1.16.3)
Requirement already satisfied: nvidia-nccl-cu13 in /usr/local/lib/python3.13/dist-packages (from xgboost->optuna-integration[xgboost]) (2.31.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.13/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (4.16.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration[xgboost]) (3.5.5)

In [41]:
from optuna.visualization import plot_intermediate_values

# 1. Plot intermediate values during the trials
plot_intermediate_values(study).show()