### ***Dataset & DataLoaders***

In [1]:
from sklearn.datasets import make_classification
import torch

# Create Our Classification Dataset
X,y = make_classification(
    n_samples=25,
    n_features=4,
    n_informative=2,
    n_redundant=0,
    random_state=42
)

In [2]:
X.shape

(25, 4)

In [3]:
y.shape

(25,)

In [4]:
import pandas as pd
df = pd.DataFrame(X)
df.head()

          0         1         2         3
0  1.477894  0.445781 -0.518270  0.060403
1  0.361636 -1.124510 -0.645120 -0.755417
2  0.091761 -0.097704 -1.987569  0.656092
3 -0.219672  0.021313  0.357113 -0.025601
4 -0.161286  0.895767  0.404051  1.958381

In [5]:
## Convert Data To PyTorch Tensors
X = torch.tensor(X,dtype=torch.float32)
y = torch.tensor(y,dtype=torch.long)

In [6]:
X

tensor([[ 1.4779,  0.4458, -0.5183,  0.0604],
        [ 0.3616, -1.1245, -0.6451, -0.7554],
        [ 0.0918, -0.0977, -1.9876,  0.6561],
        [-0.2197,  0.0213,  0.3571, -0.0256],
        [-0.1613,  0.8958,  0.4041,  1.9584],
        [-0.5298,  0.5933,  0.5133, -1.0266],
        [-0.3427,  0.8141, -0.8023,  1.0146],
        [-0.3921,  0.6779, -1.4635,  0.4168],
        [ 0.9154,  0.7276,  0.3288, -1.8472],
        [-0.8085, -1.4061, -0.5018,  1.3980],
        [-1.1063, -2.7611, -1.1962,  0.8745],
        [-0.7021,  0.4206, -0.3277, -0.1051],
        [-2.6197, -1.3831,  0.8219,  1.6846],
        [ 0.2576, -0.3776, -0.0744,  0.3013],
        [ 1.8862,  1.8981,  0.1746,  1.6146],
        [ 0.2961,  0.0232,  0.2611,  0.7651],
        [-0.0358,  0.4542,  1.5646, -2.7169],
        [-1.4154,  0.9154, -0.4206,  0.4749],
        [-0.0720, -2.7871,  1.0035,  0.7018],
        [ 0.0051,  1.5189, -0.2346,  2.0689],
        [ 0.8125, -0.6326,  1.3562, -1.3695],
        [ 0.0971,  1.7560,  0.9686, -2.8536],
        [ 0.3614, -0.2709,  1.5380, -1.7336],
        [ 0.0870, -1.8623, -0.2990,  1.8086],
        [-0.4792, -1.2391, -0.1857, -0.8344]])

In [7]:
y

tensor([1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
        0])

In [8]:
from torch.utils.data import Dataset,DataLoader

class CustomDataset(Dataset):
  def __init__(self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index],self.labels[index]

In [9]:
dataset = CustomDataset(X,y)

print(len(dataset))

25

In [10]:
dataset[4]

(tensor([-0.1613,  0.8958,  0.4041,  1.9584]), tensor(1))

In [11]:
# DataLoader
dataloader = DataLoader(dataset,batch_size=3,shuffle=False)

In [12]:
for batch_features,batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print("*"*50)

tensor([[ 1.4779,  0.4458, -0.5183,  0.0604],
        [ 0.3616, -1.1245, -0.6451, -0.7554],
        [ 0.0918, -0.0977, -1.9876,  0.6561]])
tensor([1, 0, 1])
**************************************************
tensor([[-0.2197,  0.0213,  0.3571, -0.0256],
        [-0.1613,  0.8958,  0.4041,  1.9584],
        [-0.5298,  0.5933,  0.5133, -1.0266]])
tensor([1, 1, 0])
**************************************************
tensor([[-0.3427,  0.8141, -0.8023,  1.0146],
        [-0.3921,  0.6779, -1.4635,  0.4168],
        [ 0.9154,  0.7276,  0.3288, -1.8472]])
tensor([1, 0, 0])
**************************************************
tensor([[-0.8085, -1.4061, -0.5018,  1.3980],
        [-1.1063, -2.7611, -1.1962,  0.8745],
        [-0.7021,  0.4206, -0.3277, -0.1051]])
tensor([1, 0, 0])
**************************************************
tensor([[-2.6197, -1.3831,  0.8219,  1.6846],
        [ 0.2576, -0.3776, -0.0744,  0.3013],
        [ 1.8862,  1.8981,  0.1746,  1.6146]])
tensor([1, 1, 1])
**************************************************
tensor([[ 0.2961,  0.0232,  0.2611,  0.7651],
        [-0.0358,  0.4542,  1.5646, -2.7169],
        [-1.4154,  0.9154, -0.4206,  0.4749]])
tensor([0, 0, 1])
**************************************************
tensor([[-0.0720, -2.7871,  1.0035,  0.7018],
        [ 0.0051,  1.5189, -0.2346,  2.0689],
        [ 0.8125, -0.6326,  1.3562, -1.3695]])
tensor([0, 1, 0])
**************************************************
tensor([[ 0.0971,  1.7560,  0.9686, -2.8536],
        [ 0.3614, -0.2709,  1.5380, -1.7336],
        [ 0.0870, -1.8623, -0.2990,  1.8086]])
tensor([0, 0, 1])
**************************************************
tensor([[-0.4792, -1.2391, -0.1857, -0.8344]])
tensor([0])
**************************************************

### ***Working With RealWorld Dataset***

In [13]:
import numpy as no
import pandas as pd
import torch

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

# load Our Dataset
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [14]:
df.shape

(569, 33)

In [15]:
df.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,0.0
mean,3.037183e+07,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,NaN
std,1.250206e+08,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,NaN
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,NaN
25%,8.692180e+05,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,NaN
50%,9.060240e+05,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,NaN
75%,8.813129e+06,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,NaN
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,NaN

In [16]:
U = df.iloc[:, 1:]
v = df.iloc[:, 0]

In [17]:
U.shape

(569, 32)

In [18]:
## Train Test Split
X = df.drop(['diagnosis','id','Unnamed: 32'],axis=1)
y = df['diagnosis']

In [19]:
X.shape

(569, 30)

In [20]:
## Perform Train Test Split
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [21]:
X_train.shape

(455, 30)

In [22]:
X_test.shape

(114, 30)

In [23]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [24]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [25]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

In [26]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [27]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0])

In [28]:
## Numpy arrays to PyTorch tensors
import numpy as np

X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))

y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [29]:
X_train_tensor.shape

torch.Size([455, 30])

In [30]:
y_train_tensor.shape

torch.Size([455])

### ***Build Dataset & DataLoader Class***

In [31]:
from torch.utils.data import Dataset,DataLoader

class DatasetClass(Dataset):
  def __init__(self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self,idx):
    return self.features[idx],self.labels[idx]

In [32]:
train_dataset = DatasetClass(X_train_tensor,y_train_tensor)
test_dataset = DatasetClass(X_test_tensor,y_test_tensor)

In [33]:
train_dataset[5]

(tensor([ 0.1196,  1.9607,  0.1995,  0.0125,  1.3055,  1.0662,  0.9448,  0.6670,
          1.7919,  1.1127, -0.1132, -0.3136,  0.0100, -0.1594, -0.4526,  0.9020,
          0.4543, -0.1581, -0.2454,  0.5911,  0.2549,  1.9137,  0.5098,  0.1168,
          1.5730,  2.6153,  2.0462,  0.8738,  2.0814,  2.8176]),
 tensor(1.))

In [34]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [35]:
train_loader

### ***Build Our Model***

In [36]:
import torch
import torch.nn as nn

class Simple_NN(nn.Module):
  def __init__(self,input_features):
    super().__init__()
    self.linear = nn.Linear(input_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    output = self.linear(features)
    output = self.sigmoid(output)
    return output

In [37]:
model = Simple_NN(X_train_tensor.shape[1])
optimizer = torch.optim.Adam(model.parameters(),lr=0.2)
loss_func = nn.BCELoss()

In [38]:
## Training Pipeline (Manual Created)
epochs = 30
for epoch in range(epochs):
  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)

    # loss calculate
    loss = loss_func(y_pred, batch_labels.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.27219146490097046
Epoch: 2, Loss: 4.476352842175402e-05
Epoch: 3, Loss: 0.004473154433071613
Epoch: 4, Loss: 0.010941646061837673
Epoch: 5, Loss: 0.0005880934768356383
Epoch: 6, Loss: 0.004865689668804407
Epoch: 7, Loss: 0.05943947285413742
Epoch: 8, Loss: 0.0001873529690783471
Epoch: 9, Loss: 0.00011063606507377699
Epoch: 10, Loss: 0.028868405148386955
Epoch: 11, Loss: 0.07074769586324692
Epoch: 12, Loss: 0.10382227599620819
Epoch: 13, Loss: 0.00016199627134483308
Epoch: 14, Loss: 0.001953772734850645
Epoch: 15, Loss: 0.016724903136491776
Epoch: 16, Loss: 0.0435965470969677
Epoch: 17, Loss: 9.864685125648975e-06
Epoch: 18, Loss: 1.7893802578328177e-05
Epoch: 19, Loss: 1.26825749874115
Epoch: 20, Loss: 1.108458399772644
Epoch: 21, Loss: 0.003335561603307724
Epoch: 22, Loss: 8.887920557754114e-05
Epoch: 23, Loss: 0.0001972231693798676
Epoch: 24, Loss: 0.15902788937091827
Epoch: 25, Loss: 0.00020760600455105305
Epoch: 26, Loss: 0.0032391196582466364
Epoch: 27, Loss: 1.1310103218420409e-05
Epoch: 28, Loss: 0.007007869891822338
Epoch: 29, Loss: 0.0013226584997028112
Epoch: 30, Loss: 0.0008763314108364284

In [39]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9844